In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
from keras.datasets import imdb
from keras.preprocessing import sequence
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length) 


Using TensorFlow backend.


In [4]:
# GcForeest
import argparse
import numpy as np
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/imbd.json")  
gc = GCForest(config)

In [5]:
# number of class
len(np.unique(y_train))

2

In [6]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 18:35:46,775][cascade_classifier.fit_transform] X_groups_train.shape=[(25000, 500)],y_train.shape=(25000,),X_groups_test.shape=[(25000, 500)],y_test.shape=(25000,)
[ 2018-07-31 18:35:46,803][cascade_classifier.fit_transform] group_dims=[500]
[ 2018-07-31 18:35:46,804][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 18:35:46,805][cascade_classifier.fit_transform] group_ends=[500]
[ 2018-07-31 18:35:46,806][cascade_classifier.fit_transform] X_train.shape=(25000, 500),X_test.shape=(25000, 500)
[ 2018-07-31 18:35:46,874][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(25000, 500), X_cur_test.shape=(25000, 500)
[ 2018-07-31 18:35:52,057][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=52.28%
[ 2018-07-31 18:35:57,337][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=54.40%
[ 2018-07-31 18:36:02,606][kfold_wrapper.log_eval_metrics] Accuracy(layer_0

[ 2018-07-31 18:44:17,159][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=52.84%
[ 2018-07-31 18:44:17,160][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=53.50%
[ 2018-07-31 18:44:58,439][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=58.72%
[ 2018-07-31 18:45:42,094][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=58.60%
[ 2018-07-31 18:46:22,934][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=57.28%
[ 2018-07-31 18:47:04,062][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=55.48%
[ 2018-07-31 18:47:46,291][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=54.24%
[ 2018-07-31 18:48:26,267][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=53.40%
[ 

[ 2018-07-31 19:00:12,371][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=53.55%
[ 2018-07-31 19:00:12,373][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=54.95%
[ 2018-07-31 19:00:17,540][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=52.64%
[ 2018-07-31 19:00:22,912][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=50.92%
[ 2018-07-31 19:00:27,562][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=54.24%
[ 2018-07-31 19:00:32,546][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=53.00%
[ 2018-07-31 19:00:37,491][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=53.48%
[ 2018-07-31 19:00:45,480][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=54.04%
[ 

[ 2018-07-31 19:15:51,019][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=53.42%
[ 2018-07-31 19:15:51,020][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=55.81%, accuracy_test=53.52%


In [7]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 19:15:51,198][cascade_classifier.transform] X_groups_test.shape=[(25000, 500)]
[ 2018-07-31 19:15:51,206][cascade_classifier.transform] group_dims=[500]
[ 2018-07-31 19:15:51,207][cascade_classifier.transform] X_test.shape=(25000, 500)
[ 2018-07-31 19:15:51,240][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(25000, 500)
[ 2018-07-31 19:15:57,806][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(25000, 506)


Test Accuracy of GCForest = 53.524000 %


In [8]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '2417.736', ' seconds')
[[7094 5406]
 [6213 6287]]


             precision    recall  f1-score   support

          0       0.53      0.57      0.55     12500
          1       0.54      0.50      0.52     12500

avg / total       0.54      0.54      0.53     25000



# Neural network

In [9]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Epoch 1/50
22500/22500 [==============================] - 6s 280us/step - loss: 8.0346 - acc: 0.5014
Epoch 2/50
22500/22500 [==============================] - 7s 291us/step - loss: 8.0354 - acc: 0.5015
Epoch 3/50
22500/22500 [==============================] - 6s 267us/step - loss: 8.0354 - acc: 0.5015
Epoch 4/50
22500/22500 [==============================] - 6s 259us/step - loss: 8.0354 - acc: 0.5015
Epoch 5/50
22500/22500 [==============================] - 6s 261us/step - loss: 8.0354 - acc: 0.5015
Epoch 6/50
22500/22500 [==============================] - 6s 260us/step - loss: 8.0354 - acc: 0.5015
Epoch 7/50
22500/22500 [==============================] - 6s 260us/step - loss: 8.0354 - acc: 0.5015
Epoch 8/50
22500/22500 [==============================] - 6s 260us/step - loss: 8.0354 - acc: 0.5015
Epoch 9/50
22500/22500 [==============================] - 6s 261us/step - loss: 8.0354 - acc: 0.5015
Epoch 10/50
22500/22500 [==============================] - 6s 273us/step - loss: 8.0354 - a

22500/22500 [==============================] - 7s 291us/step - loss: 8.0490 - acc: 0.5006
Epoch 31/50
22500/22500 [==============================] - 6s 275us/step - loss: 8.0490 - acc: 0.5006
Epoch 32/50
22500/22500 [==============================] - 6s 270us/step - loss: 8.0490 - acc: 0.5006
Epoch 33/50
22500/22500 [==============================] - 6s 269us/step - loss: 8.0490 - acc: 0.5006
Epoch 34/50
22500/22500 [==============================] - 6s 271us/step - loss: 8.0490 - acc: 0.5006
Epoch 35/50
22500/22500 [==============================] - 6s 268us/step - loss: 8.0490 - acc: 0.5006
Epoch 36/50
22500/22500 [==============================] - 6s 267us/step - loss: 8.0490 - acc: 0.5006
Epoch 37/50
22500/22500 [==============================] - 6s 267us/step - loss: 8.0490 - acc: 0.5006
Epoch 38/50
22500/22500 [==============================] - 6s 276us/step - loss: 8.0490 - acc: 0.5006
Epoch 39/50
22500/22500 [==============================] - 6s 277us/step - loss: 8.0490 - acc:

22500/22500 [==============================] - 6s 270us/step - loss: 7.9754 - acc: 0.4997
Epoch 10/50
22500/22500 [==============================] - 6s 275us/step - loss: 7.9754 - acc: 0.4997
Epoch 11/50
22500/22500 [==============================] - 6s 273us/step - loss: 7.9754 - acc: 0.4997
Epoch 12/50
22500/22500 [==============================] - 6s 273us/step - loss: 7.9754 - acc: 0.4997
Epoch 13/50
22500/22500 [==============================] - 6s 274us/step - loss: 7.9754 - acc: 0.4997
Epoch 14/50
22500/22500 [==============================] - 8s 370us/step - loss: 7.9754 - acc: 0.4997
Epoch 15/50
22500/22500 [==============================] - 6s 287us/step - loss: 7.9754 - acc: 0.4997
Epoch 16/50
22500/22500 [==============================] - 7s 297us/step - loss: 7.9754 - acc: 0.4997
Epoch 17/50
22500/22500 [==============================] - 6s 270us/step - loss: 7.9754 - acc: 0.4997
Epoch 18/50
22500/22500 [==============================] - 6s 274us/step - loss: 7.9754 - acc:

Epoch 39/50
22500/22500 [==============================] - 7s 332us/step - loss: 7.9747 - acc: 0.4998
Epoch 40/50
22500/22500 [==============================] - 6s 285us/step - loss: 7.9747 - acc: 0.4998
Epoch 41/50
22500/22500 [==============================] - 7s 295us/step - loss: 7.9747 - acc: 0.4998
Epoch 42/50
22500/22500 [==============================] - 7s 323us/step - loss: 7.9747 - acc: 0.4998
Epoch 43/50
22500/22500 [==============================] - 6s 275us/step - loss: 7.9747 - acc: 0.4998
Epoch 44/50
22500/22500 [==============================] - 6s 288us/step - loss: 7.9747 - acc: 0.4998
Epoch 45/50
22500/22500 [==============================] - 8s 339us/step - loss: 7.9747 - acc: 0.4998
Epoch 46/50
22500/22500 [==============================] - 6s 276us/step - loss: 7.9747 - acc: 0.4998
Epoch 47/50
22500/22500 [==============================] - 9s 379us/step - loss: 7.9747 - acc: 0.4998
Epoch 48/50
22500/22500 [==============================] - 8s 367us/step - loss: 7

22500/22500 [==============================] - 6s 282us/step - loss: 7.9832 - acc: 0.4992
Epoch 19/50
22500/22500 [==============================] - 7s 302us/step - loss: 7.9832 - acc: 0.4992
Epoch 20/50
22500/22500 [==============================] - 7s 319us/step - loss: 7.9832 - acc: 0.4992
Epoch 21/50
22500/22500 [==============================] - 7s 290us/step - loss: 7.9832 - acc: 0.4992
Epoch 22/50
22500/22500 [==============================] - 6s 285us/step - loss: 7.9832 - acc: 0.4992
Epoch 23/50
22500/22500 [==============================] - 9s 390us/step - loss: 7.9832 - acc: 0.4992
Epoch 24/50
22500/22500 [==============================] - 8s 349us/step - loss: 7.9832 - acc: 0.4992
Epoch 25/50
22500/22500 [==============================] - 6s 282us/step - loss: 7.9832 - acc: 0.4992
Epoch 26/50
22500/22500 [==============================] - 10s 449us/step - loss: 7.9832 - acc: 0.4992
Epoch 27/50
22500/22500 [==============================] - 7s 310us/step - loss: 7.9832 - acc

22500/22500 [==============================] - 6s 280us/step - loss: 8.0727 - acc: 0.4992
Epoch 48/50
22500/22500 [==============================] - 7s 300us/step - loss: 8.0727 - acc: 0.4992
Epoch 49/50
22500/22500 [==============================] - 6s 284us/step - loss: 8.0727 - acc: 0.4992
Epoch 50/50
2500/2500 [==============================] - 0s 118us/step
Epoch 1/50
22500/22500 [==============================] - 7s 298us/step - loss: 8.0562 - acc: 0.5001
Epoch 2/50
22500/22500 [==============================] - 6s 275us/step - loss: 8.0583 - acc: 0.5000
Epoch 3/50
22500/22500 [==============================] - 6s 278us/step - loss: 8.0583 - acc: 0.5000
Epoch 4/50
22500/22500 [==============================] - 7s 298us/step - loss: 8.0583 - acc: 0.5000
Epoch 5/50
22500/22500 [==============================] - 8s 356us/step - loss: 8.0583 - acc: 0.5000
Epoch 6/50
22500/22500 [==============================] - 6s 286us/step - loss: 8.0583 - acc: 0.5000
Epoch 7/50
22500/22500 [=====

22500/22500 [==============================] - 7s 313us/step - loss: 8.0813 - acc: 0.4986
Epoch 27/50
22500/22500 [==============================] - 6s 286us/step - loss: 8.0813 - acc: 0.4986
Epoch 28/50
22500/22500 [==============================] - 6s 284us/step - loss: 8.0813 - acc: 0.4986
Epoch 29/50
22500/22500 [==============================] - 6s 288us/step - loss: 8.0813 - acc: 0.4986
Epoch 30/50
22500/22500 [==============================] - 6s 285us/step - loss: 8.0813 - acc: 0.4986
Epoch 31/50
22500/22500 [==============================] - 6s 287us/step - loss: 8.0813 - acc: 0.4986
Epoch 32/50
22500/22500 [==============================] - 8s 375us/step - loss: 8.0813 - acc: 0.4986
Epoch 33/50
22500/22500 [==============================] - 6s 281us/step - loss: 8.0813 - acc: 0.4986
Epoch 34/50
22500/22500 [==============================] - 7s 296us/step - loss: 8.0813 - acc: 0.4986
Epoch 35/50
22500/22500 [==============================] - 7s 306us/step - loss: 8.0813 - acc:

# DecisionTreeClassifier

In [10]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 50.720000 %
(' Time ', '8.001', ' seconds')
[[6400 6100]
 [6220 6280]]


             precision    recall  f1-score   support

          0       0.51      0.51      0.51     12500
          1       0.51      0.50      0.50     12500

avg / total       0.51      0.51      0.51     25000



# RandomForestClassifier

In [11]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 53.060000 %
(' Time ', '28.021', ' seconds')
[[7162 5338]
 [6397 6103]]


             precision    recall  f1-score   support

          0       0.53      0.57      0.55     12500
          1       0.53      0.49      0.51     12500

avg / total       0.53      0.53      0.53     25000



# ExtraTreesClassifier

In [12]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 51.828000 %
(' Time ', '19.606', ' seconds')
[[7260 5240]
 [6803 5697]]


             precision    recall  f1-score   support

          0       0.52      0.58      0.55     12500
          1       0.52      0.46      0.49     12500

avg / total       0.52      0.52      0.52     25000



# AdaBoostClassifier

In [13]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 54.508000 %
(' Time ', '57.975', ' seconds')
[[7135 5365]
 [6008 6492]]


             precision    recall  f1-score   support

          0       0.54      0.57      0.56     12500
          1       0.55      0.52      0.53     12500

avg / total       0.55      0.55      0.54     25000



# Naive_bayes  GaussianNB

In [14]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 50.416000 %
(' Time ', '0.459', ' seconds')
[[10032  2468]
 [ 9928  2572]]


             precision    recall  f1-score   support

          0       0.50      0.80      0.62     12500
          1       0.51      0.21      0.29     12500

avg / total       0.51      0.50      0.46     25000

