In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('PenDigits_withoutdupl_norm_v01.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

att1   att2  att3  att4  att5  att6  att7  att8   att9  att10  att11  \
0  48.0  100.0  20.0  80.0   0.0  51.0  55.0  43.0  100.0   56.0   90.0   
1  38.0  100.0   4.0  85.0   0.0  53.0  58.0  46.0  100.0   52.0   88.0   
2  53.0  100.0  25.0  70.0   0.0  39.0  50.0  34.0  100.0   42.0   85.0   
3  12.0  100.0   0.0  71.0  25.0  43.0  86.0  44.0  100.0   75.0   90.0   
4  26.0  100.0   0.0  83.0  23.0  51.0  83.0  42.0  100.0   55.0   79.0   

   att12  att13  att14  att15  att16  outlier  
0   62.0   86.0   30.0   73.0    0.0        1  
1   64.0   78.0   32.0   73.0    0.0        1  
2   64.0   77.0   32.0   80.0    0.0        1  
3   52.0   90.0   20.0   90.0    0.0        1  
4   84.0   56.0   42.0   37.0    0.0        1

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/Pendigits.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,16]
X = df[:,0:16]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0=time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:11:18,721][cascade_classifier.fit_transform] X_groups_train.shape=[(6907, 16)],y_train.shape=(6907,),X_groups_test.shape=[(2961, 16)],y_test.shape=(2961,)
[ 2018-07-31 22:11:18,724][cascade_classifier.fit_transform] group_dims=[16]
[ 2018-07-31 22:11:18,726][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:11:18,727][cascade_classifier.fit_transform] group_ends=[16]
[ 2018-07-31 22:11:18,728][cascade_classifier.fit_transform] X_train.shape=(6907, 16),X_test.shape=(2961, 16)
[ 2018-07-31 22:11:18,730][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(6907, 16), X_cur_test.shape=(2961, 16)
[ 2018-07-31 22:11:19,616][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=99.71%
[ 2018-07-31 22:11:20,751][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=100.00%
[ 2018-07-31 22:11:21,846][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 

[ 2018-07-31 22:12:05,859][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=99.96%
[ 2018-07-31 22:12:05,895][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=100.00%
[ 2018-07-31 22:12:06,093][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=99.86%
[ 2018-07-31 22:12:06,490][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=99.71%
[ 2018-07-31 22:12:06,817][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=100.00%
[ 2018-07-31 22:12:07,062][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=100.00%
[ 2018-07-31 22:12:07,275][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=99.71%
[ 2018-07-31 22:12:07,559][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=99.57%

[ 2018-07-31 22:12:54,412][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=99.91%
[ 2018-07-31 22:12:54,413][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=100.00%
[ 2018-07-31 22:12:55,366][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=99.86%
[ 2018-07-31 22:12:56,554][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=100.00%
[ 2018-07-31 22:12:57,662][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=100.00%
[ 2018-07-31 22:12:59,134][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=99.71%
[ 2018-07-31 22:13:00,510][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=99.71%
[ 2018-07-31 22:13:01,899][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=100.00

In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 22:13:09,885][cascade_classifier.transform] X_groups_test.shape=[(2961, 16)]
[ 2018-07-31 22:13:09,893][cascade_classifier.transform] group_dims=[16]
[ 2018-07-31 22:13:09,897][cascade_classifier.transform] X_test.shape=(2961, 16)
[ 2018-07-31 22:13:09,898][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(2961, 16)


Test Accuracy of GCForest = 100.000000 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '116.388', ' seconds')
[[2957    0]
 [   0    4]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       1.00      1.00      1.00         4

avg / total       1.00      1.00      1.00      2961



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
6216/6216 [==============================] - 4s 585us/step - loss: 0.0542 - acc: 0.9924
Epoch 2/50
6216/6216 [==============================] - 3s 423us/step - loss: 0.0415 - acc: 0.9974
Epoch 3/50
6216/6216 [==============================] - 3s 442us/step - loss: 0.0415 - acc: 0.9974
Epoch 4/50
6216/6216 [==============================] - 3s 410us/step - loss: 0.0415 - acc: 0.9974
Epoch 5/50
6216/6216 [==============================] - 3s 454us/step - loss: 0.0415 - acc: 0.9974
Epoch 6/50
6216/6216 [==============================] - 3s 464us/step - loss: 0.0415 - acc: 0.9974
Epoch 7/50
6216/6216 [==============================] - 3s 494us/step - loss: 0.0415 - acc: 0.9974
Epoch 8/50
6216/6216 [==============================] - 3s 526us/step - loss: 0.0415 - acc: 0.9974
Epoch 9/50
6216/6216 [==============================] - 3s 555us/step - loss: 0.0415 - acc: 0.9974
Epoch 10/50
6216/6216 [==============================] - 3s 492us/step - loss: 0.0415 - acc: 0.9974
Epoch 11/

6216/6216 [==============================] - 5s 759us/step - loss: 0.0311 - acc: 0.9981
Epoch 33/50
6216/6216 [==============================] - 4s 681us/step - loss: 0.0311 - acc: 0.9981
Epoch 34/50
6216/6216 [==============================] - 4s 621us/step - loss: 0.0311 - acc: 0.9981
Epoch 35/50
6216/6216 [==============================] - 4s 644us/step - loss: 0.0311 - acc: 0.9981
Epoch 36/50
6216/6216 [==============================] - 4s 669us/step - loss: 0.0311 - acc: 0.9981
Epoch 37/50
6216/6216 [==============================] - 4s 648us/step - loss: 0.0311 - acc: 0.9981
Epoch 38/50
6216/6216 [==============================] - 4s 692us/step - loss: 0.0311 - acc: 0.9981
Epoch 39/50
6216/6216 [==============================] - 4s 669us/step - loss: 0.0311 - acc: 0.9981
Epoch 40/50
6216/6216 [==============================] - 3s 555us/step - loss: 0.0311 - acc: 0.9981
Epoch 41/50
6216/6216 [==============================] - 3s 527us/step - loss: 0.0311 - acc: 0.9981
Epoch 42/50


6216/6216 [==============================] - 4s 724us/step - loss: 0.0415 - acc: 0.9974 1s - loss: 0.0
Epoch 13/50
6216/6216 [==============================] - 4s 717us/step - loss: 0.0415 - acc: 0.9974
Epoch 14/50
6216/6216 [==============================] - 4s 656us/step - loss: 0.0415 - acc: 0.9974
Epoch 15/50
6216/6216 [==============================] - 4s 649us/step - loss: 0.0415 - acc: 0.9974
Epoch 16/50
6216/6216 [==============================] - 3s 533us/step - loss: 0.0415 - acc: 0.9974
Epoch 17/50
6216/6216 [==============================] - 4s 605us/step - loss: 0.0415 - acc: 0.9974
Epoch 18/50
6216/6216 [==============================] - 4s 598us/step - loss: 0.0415 - acc: 0.9974
Epoch 19/50
6216/6216 [==============================] - 5s 784us/step - loss: 0.0415 - acc: 0.9974 1s - lo
Epoch 20/50
6216/6216 [==============================] - 4s 674us/step - loss: 0.0415 - acc: 0.9974
Epoch 21/50
6216/6216 [==============================] - 4s 577us/step - loss: 0.0415 - a

6216/6216 [==============================] - 4s 643us/step - loss: 0.0389 - acc: 0.9976
Epoch 43/50
6216/6216 [==============================] - 4s 589us/step - loss: 0.0389 - acc: 0.9976
Epoch 44/50
6216/6216 [==============================] - 3s 542us/step - loss: 0.0389 - acc: 0.9976
Epoch 45/50
6216/6216 [==============================] - 4s 588us/step - loss: 0.0389 - acc: 0.9976
Epoch 46/50
6216/6216 [==============================] - 5s 735us/step - loss: 0.0389 - acc: 0.9976
Epoch 47/50
6216/6216 [==============================] - 4s 681us/step - loss: 0.0389 - acc: 0.9976 0s - loss: 0.0438 -
Epoch 48/50
6216/6216 [==============================] - 4s 647us/step - loss: 0.0389 - acc: 0.9976
Epoch 49/50
6216/6216 [==============================] - 4s 649us/step - loss: 0.0389 - acc: 0.9976
Epoch 50/50
691/691 [==============================] - 0s 622us/step
Epoch 1/50
6216/6216 [==============================] - 5s 842us/step - loss: 0.0269 - acc: 0.9984
Epoch 2/50
6216/6216 [==

6216/6216 [==============================] - 2s 385us/step - loss: 0.0389 - acc: 0.9976
Epoch 23/50
6216/6216 [==============================] - 2s 376us/step - loss: 0.0389 - acc: 0.9976
Epoch 24/50
6216/6216 [==============================] - 2s 385us/step - loss: 0.0389 - acc: 0.9976
Epoch 25/50
6216/6216 [==============================] - 2s 377us/step - loss: 0.0389 - acc: 0.9976
Epoch 26/50
6216/6216 [==============================] - 2s 391us/step - loss: 0.0389 - acc: 0.9976
Epoch 27/50
6216/6216 [==============================] - 3s 422us/step - loss: 0.0389 - acc: 0.9976
Epoch 28/50
6216/6216 [==============================] - 3s 422us/step - loss: 0.0389 - acc: 0.9976
Epoch 29/50
6216/6216 [==============================] - 3s 432us/step - loss: 0.0389 - acc: 0.9976
Epoch 30/50
6216/6216 [==============================] - 3s 405us/step - loss: 0.0389 - acc: 0.9976
Epoch 31/50
6216/6216 [==============================] - 2s 384us/step - loss: 0.0389 - acc: 0.9976
Epoch 32/50


6217/6217 [==============================] - 2s 401us/step - loss: 0.0415 - acc: 0.9974
Epoch 4/50
6217/6217 [==============================] - 2s 382us/step - loss: 0.0415 - acc: 0.9974
Epoch 5/50
6217/6217 [==============================] - 2s 381us/step - loss: 0.0415 - acc: 0.9974
Epoch 6/50
6217/6217 [==============================] - 2s 389us/step - loss: 0.0415 - acc: 0.9974
Epoch 7/50
6217/6217 [==============================] - 2s 379us/step - loss: 0.0415 - acc: 0.9974
Epoch 8/50
6217/6217 [==============================] - 2s 388us/step - loss: 0.0415 - acc: 0.9974
Epoch 9/50
6217/6217 [==============================] - 2s 380us/step - loss: 0.0415 - acc: 0.9974
Epoch 10/50
6217/6217 [==============================] - 2s 378us/step - loss: 0.0415 - acc: 0.9974
Epoch 11/50
6217/6217 [==============================] - 2s 383us/step - loss: 0.0415 - acc: 0.9974
Epoch 12/50
6217/6217 [==============================] - 2s 383us/step - loss: 0.0415 - acc: 0.9974
Epoch 13/50
6217/6

6217/6217 [==============================] - 2s 271us/step - loss: 0.0389 - acc: 0.9976
Epoch 35/50
6217/6217 [==============================] - 2s 277us/step - loss: 0.0389 - acc: 0.9976
Epoch 36/50
6217/6217 [==============================] - 2s 275us/step - loss: 0.0389 - acc: 0.9976
Epoch 37/50
6217/6217 [==============================] - 2s 272us/step - loss: 0.0389 - acc: 0.9976
Epoch 38/50
6217/6217 [==============================] - 2s 275us/step - loss: 0.0389 - acc: 0.9976
Epoch 39/50
6217/6217 [==============================] - 2s 286us/step - loss: 0.0389 - acc: 0.9976
Epoch 40/50
6217/6217 [==============================] - 2s 285us/step - loss: 0.0389 - acc: 0.9976
Epoch 41/50
6217/6217 [==============================] - 2s 274us/step - loss: 0.0389 - acc: 0.9976
Epoch 42/50
6217/6217 [==============================] - 2s 278us/step - loss: 0.0389 - acc: 0.9976
Epoch 43/50
6217/6217 [==============================] - 2s 295us/step - loss: 0.0389 - acc: 0.9976
Epoch 44/50


# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 99.831138 %
(' Time ', '0.03', ' seconds')
[[2953    4]
 [   1    3]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       0.43      0.75      0.55         4

avg / total       1.00      1.00      1.00      2961



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 99.932455 %
(' Time ', '1.095', ' seconds')
[[2957    0]
 [   2    2]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       1.00      0.50      0.67         4

avg / total       1.00      1.00      1.00      2961



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 99.966228 %
(' Time ', '1.048', ' seconds')
[[2957    0]
 [   1    3]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       1.00      0.75      0.86         4

avg / total       1.00      1.00      1.00      2961



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 99.932455 %
(' Time ', '1.825', ' seconds')
[[2957    0]
 [   2    2]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       1.00      0.50      0.67         4

avg / total       1.00      1.00      1.00      2961



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 99.527187 %
(' Time ', '0.009', ' seconds')
[[2944   13]
 [   1    3]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2957
        1.0       0.19      0.75      0.30         4

avg / total       1.00      1.00      1.00      2961

