In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('diabetes.csv')  

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/aloi.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,8]
X = df[:,0:8]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/kader/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2019-01-12 10:38:55,802][cascade_classifier.fit_transform] X_groups_train.shape=[(537, 8)],y_train.shape=(537,),X_groups_test.shape=[(231, 8)],y_test.shape=(231,)
[ 2019-01-12 10:38:55,806][cascade_classifier.fit_transform] group_dims=[8]
[ 2019-01-12 10:38:55,810][cascade_classifier.fit_transform] group_starts=[0]
[ 2019-01-12 10:38:55,812][cascade_classifier.fit_transform] group_ends=[8]
[ 2019-01-12 10:38:55,813][cascade_classifier.fit_transform] X_train.shape=(537, 8),X_test.shape=(231, 8)
[ 2019-01-12 10:38:55,815][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(537, 8), X_cur_test.shape=(231, 8)
[ 2019-01-12 10:38:56,500][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=72.73%
[ 2019-01-12 10:38:57,328][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=70.91%
[ 2019-01-12 10:38:58,102][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_

[ 2019-01-12 10:39:27,571][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=76.16%
[ 2019-01-12 10:39:27,572][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=75.76%
[ 2019-01-12 10:39:27,588][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=72.73%
[ 2019-01-12 10:39:27,600][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=78.18%
[ 2019-01-12 10:39:27,611][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=81.82%
[ 2019-01-12 10:39:27,624][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=72.22%
[ 2019-01-12 10:39:27,637][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=86.79%
[ 2019-01-12 10:39:27,648][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=73.58%
[ 

[ 2019-01-12 10:39:51,454][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=75.05%
[ 2019-01-12 10:39:51,456][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=77.49%
[ 2019-01-12 10:39:52,108][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=58.18%
[ 2019-01-12 10:39:52,842][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=80.00%
[ 2019-01-12 10:39:53,616][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=63.64%
[ 2019-01-12 10:39:54,405][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=79.63%
[ 2019-01-12 10:39:55,184][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=77.36%
[ 2019-01-12 10:39:55,962][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=81.13%
[ 

[ 2019-01-12 10:40:15,344][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=77.92%
[ 2019-01-12 10:40:15,347][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=75.42%, accuracy_test=76.62%


In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

[ 2019-01-12 10:40:15,366][cascade_classifier.transform] X_groups_test.shape=[(231, 8)]
[ 2019-01-12 10:40:15,369][cascade_classifier.transform] group_dims=[8]
[ 2019-01-12 10:40:15,375][cascade_classifier.transform] X_test.shape=(231, 8)
[ 2019-01-12 10:40:15,377][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(231, 8)
[ 2019-01-12 10:40:17,708][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(231, 14)


Test Accuracy of GCForest = 76.623377 %
(' Time ', '84.264', ' seconds')


In [9]:
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

[[136  21]
 [ 33  41]]


             precision    recall  f1-score   support

        0.0       0.80      0.87      0.83       157
        1.0       0.66      0.55      0.60        74

avg / total       0.76      0.77      0.76       231



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

Using TensorFlow backend.


Epoch 1/50
483/483 [==============================] - 2s 4ms/step - loss: 2.1668 - acc: 0.5114
Epoch 2/50
483/483 [==============================] - 0s 712us/step - loss: 0.7151 - acc: 0.6418
Epoch 3/50
483/483 [==============================] - 0s 778us/step - loss: 0.6435 - acc: 0.6460
Epoch 4/50
483/483 [==============================] - 0s 756us/step - loss: 0.6403 - acc: 0.6460
Epoch 5/50
483/483 [==============================] - 0s 826us/step - loss: 0.6567 - acc: 0.6377
Epoch 6/50
483/483 [==============================] - 0s 673us/step - loss: 0.6034 - acc: 0.6853
Epoch 7/50
483/483 [==============================] - 0s 578us/step - loss: 0.6152 - acc: 0.6749
Epoch 8/50
483/483 [==============================] - 0s 665us/step - loss: 0.6348 - acc: 0.6915
Epoch 9/50
483/483 [==============================] - 0s 853us/step - loss: 0.6627 - acc: 0.6480
Epoch 10/50
483/483 [==============================] - 0s 773us/step - loss: 0.6004 - acc: 0.6770
Epoch 11/50
483/483 [==========

Epoch 34/50
483/483 [==============================] - 0s 890us/step - loss: 0.5219 - acc: 0.7598
Epoch 35/50
483/483 [==============================] - 0s 967us/step - loss: 0.5368 - acc: 0.7288
Epoch 36/50
483/483 [==============================] - 0s 970us/step - loss: 0.5253 - acc: 0.7453
Epoch 37/50
483/483 [==============================] - 0s 904us/step - loss: 0.6157 - acc: 0.6749
Epoch 38/50
483/483 [==============================] - 0s 828us/step - loss: 0.5315 - acc: 0.7412
Epoch 39/50
483/483 [==============================] - 0s 929us/step - loss: 0.5331 - acc: 0.7329
Epoch 40/50
483/483 [==============================] - 0s 667us/step - loss: 0.5396 - acc: 0.7267
Epoch 41/50
483/483 [==============================] - 0s 876us/step - loss: 0.5407 - acc: 0.7205
Epoch 42/50
483/483 [==============================] - 0s 775us/step - loss: 0.5464 - acc: 0.7350
Epoch 43/50
483/483 [==============================] - 0s 779us/step - loss: 0.5363 - acc: 0.7329
Epoch 44/50
483/483 

483/483 [==============================] - 0s 576us/step - loss: 0.5763 - acc: 0.7039
Epoch 17/50
483/483 [==============================] - 0s 538us/step - loss: 0.6157 - acc: 0.6687
Epoch 18/50
483/483 [==============================] - 0s 600us/step - loss: 0.6330 - acc: 0.6480
Epoch 19/50
483/483 [==============================] - 0s 658us/step - loss: 0.5784 - acc: 0.6894
Epoch 20/50
483/483 [==============================] - 0s 811us/step - loss: 0.6473 - acc: 0.6398
Epoch 21/50
483/483 [==============================] - 0s 642us/step - loss: 0.5903 - acc: 0.6936
Epoch 22/50
483/483 [==============================] - 0s 569us/step - loss: 0.5901 - acc: 0.7081
Epoch 23/50
483/483 [==============================] - 0s 783us/step - loss: 0.5732 - acc: 0.6936
Epoch 24/50
483/483 [==============================] - 0s 645us/step - loss: 0.5734 - acc: 0.6749
Epoch 25/50
483/483 [==============================] - 0s 696us/step - loss: 0.5604 - acc: 0.7019
Epoch 26/50
483/483 [===========

483/483 [==============================] - 0s 639us/step - loss: 0.5035 - acc: 0.7619
Epoch 50/50
54/54 [==============================] - 0s 2ms/step
Epoch 1/50
483/483 [==============================] - 1s 1ms/step - loss: 4.1753 - acc: 0.5797
Epoch 2/50
483/483 [==============================] - 0s 622us/step - loss: 1.4756 - acc: 0.5487
Epoch 3/50
483/483 [==============================] - 0s 693us/step - loss: 0.6983 - acc: 0.6128
Epoch 4/50
483/483 [==============================] - 0s 688us/step - loss: 0.6564 - acc: 0.6439
Epoch 5/50
483/483 [==============================] - 0s 608us/step - loss: 0.7419 - acc: 0.5818
Epoch 6/50
483/483 [==============================] - 0s 545us/step - loss: 0.6904 - acc: 0.5983
Epoch 7/50
483/483 [==============================] - 0s 593us/step - loss: 0.6144 - acc: 0.6791
Epoch 8/50
483/483 [==============================] - 0s 538us/step - loss: 0.7287 - acc: 0.6149
Epoch 9/50
483/483 [==============================] - 0s 553us/step - loss:

483/483 [==============================] - 0s 579us/step - loss: 0.5159 - acc: 0.7536
Epoch 32/50
483/483 [==============================] - 0s 551us/step - loss: 0.5259 - acc: 0.7226
Epoch 33/50
483/483 [==============================] - 0s 857us/step - loss: 0.5205 - acc: 0.7391
Epoch 34/50
483/483 [==============================] - 0s 830us/step - loss: 0.5388 - acc: 0.7329
Epoch 35/50
483/483 [==============================] - 0s 797us/step - loss: 0.5935 - acc: 0.7039
Epoch 36/50
483/483 [==============================] - 0s 731us/step - loss: 0.5370 - acc: 0.7081
Epoch 37/50
483/483 [==============================] - 0s 675us/step - loss: 0.5445 - acc: 0.7371
Epoch 38/50
483/483 [==============================] - 0s 739us/step - loss: 0.5096 - acc: 0.7495
Epoch 39/50
483/483 [==============================] - 0s 854us/step - loss: 0.5561 - acc: 0.7288
Epoch 40/50
483/483 [==============================] - 0s 791us/step - loss: 0.5210 - acc: 0.7453
Epoch 41/50
483/483 [===========

Epoch 13/50
484/484 [==============================] - 0s 527us/step - loss: 0.5593 - acc: 0.7252
Epoch 14/50
484/484 [==============================] - 0s 594us/step - loss: 0.5970 - acc: 0.6839
Epoch 15/50
484/484 [==============================] - 0s 902us/step - loss: 0.5494 - acc: 0.7149
Epoch 16/50
484/484 [==============================] - 0s 819us/step - loss: 0.5428 - acc: 0.7231
Epoch 17/50
484/484 [==============================] - 0s 876us/step - loss: 0.5628 - acc: 0.7149
Epoch 18/50
484/484 [==============================] - 0s 646us/step - loss: 0.5627 - acc: 0.7128
Epoch 19/50
484/484 [==============================] - 0s 705us/step - loss: 0.5632 - acc: 0.7128
Epoch 20/50
484/484 [==============================] - 0s 837us/step - loss: 0.5572 - acc: 0.7211
Epoch 21/50
484/484 [==============================] - 0s 767us/step - loss: 0.5374 - acc: 0.7273
Epoch 22/50
484/484 [==============================] - 0s 714us/step - loss: 0.5239 - acc: 0.7376
Epoch 23/50
484/484 

484/484 [==============================] - 0s 621us/step - loss: 0.4939 - acc: 0.7686
Epoch 46/50
484/484 [==============================] - 0s 546us/step - loss: 0.5415 - acc: 0.7004
Epoch 47/50
484/484 [==============================] - 0s 586us/step - loss: 0.5131 - acc: 0.7417
Epoch 48/50
484/484 [==============================] - 0s 564us/step - loss: 0.4961 - acc: 0.7603
Epoch 49/50
484/484 [==============================] - 0s 558us/step - loss: 0.5093 - acc: 0.7438
Epoch 50/50
53/53 [==============================] - 0s 3ms/step
Accuracy mean: 0.698008388543
Accuracy variance: 0.0663048925269


In [11]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '197.394', ' seconds')
[[136  21]
 [ 33  41]]


             precision    recall  f1-score   support

        0.0       0.80      0.87      0.83       157
        1.0       0.66      0.55      0.60        74

avg / total       0.76      0.77      0.76       231



# DecisionTreeClassifier

In [12]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of DecisionTreeClassifier = 71.428571 %
[[120  37]
 [ 29  45]]


             precision    recall  f1-score   support

        0.0       0.81      0.76      0.78       157
        1.0       0.55      0.61      0.58        74

avg / total       0.72      0.71      0.72       231

(' Time ', '0.009', ' seconds')


# RandomForestClassifier

In [13]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of RandomForestClassifier = 77.922078 %
[[139  18]
 [ 33  41]]


             precision    recall  f1-score   support

        0.0       0.81      0.89      0.84       157
        1.0       0.69      0.55      0.62        74

avg / total       0.77      0.78      0.77       231

(' Time ', '0.651', ' seconds')


# ExtraTreesClassifier

In [14]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of ExtraTreesClassifier = 77.056277 %
[[136  21]
 [ 32  42]]


             precision    recall  f1-score   support

        0.0       0.81      0.87      0.84       157
        1.0       0.67      0.57      0.61        74

avg / total       0.76      0.77      0.77       231

(' Time ', '0.521', ' seconds')


# AdaBoostClassifier

In [15]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of AdaBoostClassifier = 75.324675 %
[[136  21]
 [ 36  38]]


             precision    recall  f1-score   support

        0.0       0.79      0.87      0.83       157
        1.0       0.64      0.51      0.57        74

avg / total       0.74      0.75      0.74       231

(' Time ', '0.436', ' seconds')


# Naive_bayes  GaussianNB

In [16]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of GaussianNB = 76.190476 %
[[138  19]
 [ 36  38]]


             precision    recall  f1-score   support

        0.0       0.79      0.88      0.83       157
        1.0       0.67      0.51      0.58        74

avg / total       0.75      0.76      0.75       231

(' Time ', '0.039', ' seconds')
