In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('Annthyroid_02_v01.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

att1  att2  att3  att4  att5  att6  att7  att8  att9  att10   ...     \
0  0.73   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0   ...      
1  0.24   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   ...      
2  0.47   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   ...      
3  0.64   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   ...      
4  0.23   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   ...      

   att13  att14  att15  att16    att17  att18  att19  att20  att21  outlier  
0    0.0    0.0    0.0    0.0  0.00060  0.015  0.120  0.082  0.146        0  
1    0.0    0.0    0.0    0.0  0.00025  0.030  0.143  0.133  0.108        0  
2    0.0    0.0    0.0    0.0  0.00190  0.024  0.102  0.131  0.078        0  
3    0.0    0.0    0.0    0.0  0.00090  0.017  0.077  0.090  0.085        0  
4    0.0    0.0    0.0    0.0  0.00025  0.026  0.139  0.090  0.153        0  

[5 rows x 22 columns]

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/Annthyroid.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,21]
X = df[:,0:21]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 16:39:34,038][cascade_classifier.fit_transform] X_groups_train.shape=[(4761, 21)],y_train.shape=(4761,),X_groups_test.shape=[(2041, 21)],y_test.shape=(2041,)
[ 2018-07-31 16:39:34,040][cascade_classifier.fit_transform] group_dims=[21]
[ 2018-07-31 16:39:34,041][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 16:39:34,042][cascade_classifier.fit_transform] group_ends=[21]
[ 2018-07-31 16:39:34,043][cascade_classifier.fit_transform] X_train.shape=(4761, 21),X_test.shape=(2041, 21)
[ 2018-07-31 16:39:34,045][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(4761, 21), X_cur_test.shape=(2041, 21)
[ 2018-07-31 16:39:34,603][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=99.16%
[ 2018-07-31 16:39:35,437][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=100.00%
[ 2018-07-31 16:39:36,063][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 

[ 2018-07-31 16:40:05,203][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=99.58%
[ 2018-07-31 16:40:05,204][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=99.56%
[ 2018-07-31 16:40:05,223][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=99.16%
[ 2018-07-31 16:40:05,239][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=99.58%
[ 2018-07-31 16:40:05,254][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=99.16%
[ 2018-07-31 16:40:05,269][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=99.37%
[ 2018-07-31 16:40:05,285][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=99.58%
[ 2018-07-31 16:40:05,300][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=98.53%
[ 

[ 2018-07-31 16:40:29,900][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=99.43%
[ 2018-07-31 16:40:29,905][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=99.46%
[ 2018-07-31 16:40:30,689][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=99.16%
[ 2018-07-31 16:40:31,607][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=99.58%
[ 2018-07-31 16:40:32,714][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=99.58%
[ 2018-07-31 16:40:33,479][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=99.58%
[ 2018-07-31 16:40:34,204][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=99.58%
[ 2018-07-31 16:40:34,933][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=99.37%
[ 

[ 2018-07-31 16:40:54,512][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=99.51%
[ 2018-07-31 16:40:54,513][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=99.56%, accuracy_test=99.61%


In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 16:40:54,533][cascade_classifier.transform] X_groups_test.shape=[(2041, 21)]
[ 2018-07-31 16:40:54,534][cascade_classifier.transform] group_dims=[21]
[ 2018-07-31 16:40:54,536][cascade_classifier.transform] X_test.shape=(2041, 21)
[ 2018-07-31 16:40:54,538][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(2041, 21)
[ 2018-07-31 16:40:58,992][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(2041, 27)


Test Accuracy of GCForest = 99.608035 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '89.484', ' seconds')
[[1996    6]
 [   2   37]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2002
        1.0       0.86      0.95      0.90        39

avg / total       1.00      1.00      1.00      2041



# DecisionTreeClassifier

In [10]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 99.559040 %
(' Time ', '0.004', ' seconds')
[[1995    7]
 [   2   37]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2002
        1.0       0.84      0.95      0.89        39

avg / total       1.00      1.00      1.00      2041



# RandomForestClassifier

In [11]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 99.510044 %
(' Time ', '0.481', ' seconds')
[[1996    6]
 [   4   35]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2002
        1.0       0.85      0.90      0.88        39

avg / total       1.00      1.00      1.00      2041



# ExtraTreesClassifier

In [12]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 98.873101 %
(' Time ', '0.524', ' seconds')
[[2000    2]
 [  21   18]]


             precision    recall  f1-score   support

        0.0       0.99      1.00      0.99      2002
        1.0       0.90      0.46      0.61        39

avg / total       0.99      0.99      0.99      2041



# AdaBoostClassifier

In [13]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 99.657031 %
(' Time ', '0.513', ' seconds')
[[1998    4]
 [   3   36]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2002
        1.0       0.90      0.92      0.91        39

avg / total       1.00      1.00      1.00      2041



# Naive_bayes  GaussianNB

In [14]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 8.868202 %
(' Time ', '0.005', ' seconds')
[[ 143 1859]
 [   1   38]]


             precision    recall  f1-score   support

        0.0       0.99      0.07      0.13      2002
        1.0       0.02      0.97      0.04        39

avg / total       0.97      0.09      0.13      2041



# Neural network 

In [15]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
4284/4284 [==============================] - 1s 338us/step - loss: 0.1325 - acc: 0.9767
Epoch 2/50
4284/4284 [==============================] - 1s 238us/step - loss: 0.0882 - acc: 0.9799
Epoch 3/50
4284/4284 [==============================] - 1s 276us/step - loss: 0.0792 - acc: 0.9804
Epoch 4/50
4284/4284 [==============================] - 1s 247us/step - loss: 0.0739 - acc: 0.9827
Epoch 5/50
4284/4284 [==============================] - 1s 177us/step - loss: 0.0701 - acc: 0.9837
Epoch 6/50
4284/4284 [==============================] - 1s 166us/step - loss: 0.0701 - acc: 0.9846
Epoch 7/50
4284/4284 [==============================] - 1s 169us/step - loss: 0.0662 - acc: 0.9848
Epoch 8/50
4284/4284 [==============================] - 1s 167us/step - loss: 0.0641 - acc: 0.9851
Epoch 9/50
4284/4284 [==============================] - 1s 163us/step - loss: 0.0619 - acc: 0.9844
Epoch 10/50
4284/4284 [==============================] - 1s 168us/step - loss: 0.0614 - acc: 0.9855
Epoch 11/

4285/4285 [==============================] - 1s 205us/step - loss: 0.0276 - acc: 0.9893
Epoch 33/50
4285/4285 [==============================] - 1s 281us/step - loss: 0.0312 - acc: 0.9902
Epoch 34/50
4285/4285 [==============================] - 1s 259us/step - loss: 0.0300 - acc: 0.9900
Epoch 35/50
4285/4285 [==============================] - 1s 211us/step - loss: 0.0283 - acc: 0.9904
Epoch 36/50
4285/4285 [==============================] - 1s 206us/step - loss: 0.0279 - acc: 0.9900
Epoch 37/50
4285/4285 [==============================] - 1s 190us/step - loss: 0.0280 - acc: 0.9907
Epoch 38/50
4285/4285 [==============================] - 1s 196us/step - loss: 0.0265 - acc: 0.9902
Epoch 39/50
4285/4285 [==============================] - 1s 190us/step - loss: 0.0283 - acc: 0.9909
Epoch 40/50
4285/4285 [==============================] - 1s 191us/step - loss: 0.0290 - acc: 0.9893
Epoch 41/50
4285/4285 [==============================] - 1s 198us/step - loss: 0.0261 - acc: 0.9916
Epoch 42/50


4285/4285 [==============================] - 1s 171us/step - loss: 0.0571 - acc: 0.9855
Epoch 13/50
4285/4285 [==============================] - 1s 176us/step - loss: 0.0563 - acc: 0.9855
Epoch 14/50
4285/4285 [==============================] - 1s 172us/step - loss: 0.0560 - acc: 0.9855
Epoch 15/50
4285/4285 [==============================] - 1s 170us/step - loss: 0.0525 - acc: 0.9860
Epoch 16/50
4285/4285 [==============================] - 1s 169us/step - loss: 0.0527 - acc: 0.9858 0s - loss: 0.0525 
Epoch 17/50
4285/4285 [==============================] - 1s 170us/step - loss: 0.0486 - acc: 0.9860
Epoch 18/50
4285/4285 [==============================] - 1s 172us/step - loss: 0.0466 - acc: 0.9874
Epoch 19/50
4285/4285 [==============================] - 1s 178us/step - loss: 0.0456 - acc: 0.9867
Epoch 20/50
4285/4285 [==============================] - 1s 172us/step - loss: 0.0423 - acc: 0.9867
Epoch 21/50
4285/4285 [==============================] - 1s 169us/step - loss: 0.0444 - acc: 

4285/4285 [==============================] - 1s 174us/step - loss: 0.0245 - acc: 0.9923
Epoch 44/50
4285/4285 [==============================] - 1s 171us/step - loss: 0.0330 - acc: 0.9897
Epoch 45/50
4285/4285 [==============================] - 1s 172us/step - loss: 0.0213 - acc: 0.9930
Epoch 46/50
4285/4285 [==============================] - 1s 173us/step - loss: 0.0265 - acc: 0.9911
Epoch 47/50
4285/4285 [==============================] - 1s 172us/step - loss: 0.0237 - acc: 0.9918
Epoch 48/50
4285/4285 [==============================] - 1s 169us/step - loss: 0.0203 - acc: 0.9930
Epoch 49/50
4285/4285 [==============================] - 1s 177us/step - loss: 0.0201 - acc: 0.9942
Epoch 50/50
476/476 [==============================] - 0s 167us/step
Epoch 1/50
4285/4285 [==============================] - 1s 311us/step - loss: 0.1364 - acc: 0.9725
Epoch 2/50
4285/4285 [==============================] - 1s 175us/step - loss: 0.0868 - acc: 0.9799
Epoch 3/50
4285/4285 [=======================

4285/4285 [==============================] - 1s 177us/step - loss: 0.0427 - acc: 0.9862
Epoch 25/50
4285/4285 [==============================] - 1s 169us/step - loss: 0.0438 - acc: 0.9869
Epoch 26/50
4285/4285 [==============================] - 1s 170us/step - loss: 0.0405 - acc: 0.9867
Epoch 27/50
4285/4285 [==============================] - 1s 173us/step - loss: 0.0434 - acc: 0.9869
Epoch 28/50
4285/4285 [==============================] - 1s 174us/step - loss: 0.0423 - acc: 0.9876
Epoch 29/50
4285/4285 [==============================] - 1s 175us/step - loss: 0.0347 - acc: 0.9883
Epoch 30/50
4285/4285 [==============================] - 1s 179us/step - loss: 0.0316 - acc: 0.9876
Epoch 31/50
4285/4285 [==============================] - 1s 173us/step - loss: 0.0333 - acc: 0.9881
Epoch 32/50
4285/4285 [==============================] - 1s 209us/step - loss: 0.0326 - acc: 0.9886
Epoch 33/50
4285/4285 [==============================] - 1s 240us/step - loss: 0.0287 - acc: 0.9895
Epoch 34/50


4285/4285 [==============================] - 1s 286us/step - loss: 0.0731 - acc: 0.9830
Epoch 6/50
4285/4285 [==============================] - 1s 250us/step - loss: 0.0688 - acc: 0.9839
Epoch 7/50
4285/4285 [==============================] - 1s 222us/step - loss: 0.0693 - acc: 0.9844
Epoch 8/50
4285/4285 [==============================] - 1s 190us/step - loss: 0.0670 - acc: 0.9844
Epoch 9/50
4285/4285 [==============================] - 1s 181us/step - loss: 0.0649 - acc: 0.9846
Epoch 10/50
4285/4285 [==============================] - 1s 198us/step - loss: 0.0618 - acc: 0.9848
Epoch 11/50
4285/4285 [==============================] - 1s 199us/step - loss: 0.0617 - acc: 0.9846
Epoch 12/50
4285/4285 [==============================] - 1s 193us/step - loss: 0.0595 - acc: 0.9853
Epoch 13/50
4285/4285 [==============================] - 1s 177us/step - loss: 0.0611 - acc: 0.9851
Epoch 14/50
4285/4285 [==============================] - 1s 177us/step - loss: 0.0578 - acc: 0.9858
Epoch 15/50
4285

4285/4285 [==============================] - 1s 204us/step - loss: 0.0289 - acc: 0.9904
Epoch 37/50
4285/4285 [==============================] - 1s 188us/step - loss: 0.0325 - acc: 0.9902
Epoch 38/50
4285/4285 [==============================] - 1s 205us/step - loss: 0.0263 - acc: 0.9904
Epoch 39/50
4285/4285 [==============================] - 1s 176us/step - loss: 0.0326 - acc: 0.9897
Epoch 40/50
4285/4285 [==============================] - 1s 177us/step - loss: 0.0327 - acc: 0.9888
Epoch 41/50
4285/4285 [==============================] - 1s 179us/step - loss: 0.0290 - acc: 0.9918
Epoch 42/50
4285/4285 [==============================] - 1s 177us/step - loss: 0.0258 - acc: 0.9916
Epoch 43/50
4285/4285 [==============================] - 1s 176us/step - loss: 0.0236 - acc: 0.9909
Epoch 44/50
4285/4285 [==============================] - 1s 178us/step - loss: 0.0259 - acc: 0.9918
Epoch 45/50
4285/4285 [==============================] - 1s 262us/step - loss: 0.0217 - acc: 0.9904
Epoch 46/50
