In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('PageBlocks_withoutdupl_02_v02.csv')  

del df['id']
del df['Unnamed: 0']

df.head()

att1  att2   att3   att4   att5   att6  att7  att8  att9  att10  outlier
0   5.0   7.0   35.0  1.400  0.400  0.657  2.33  14.0  23.0    6.0        0
1   6.0   7.0   42.0  1.167  0.429  0.881  3.60  18.0  37.0    5.0        0
2   6.0  18.0  108.0  3.000  0.287  0.741  4.43  31.0  80.0    7.0        0
3   5.0   7.0   35.0  1.400  0.371  0.743  4.33  13.0  26.0    3.0        0
4   6.0   3.0   18.0  0.500  0.500  0.944  2.25   9.0  17.0    4.0        0

In [3]:
df.shape

(4982, 11)

In [4]:
# df to values
df = df.values

In [5]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/PageBlocks.json")   
gc = GCForest(config)

In [6]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,10]
X = df[:,0:10]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
# number of class
len(np.unique(y_train))

2

In [8]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:11:04,111][cascade_classifier.fit_transform] X_groups_train.shape=[(3487, 10)],y_train.shape=(3487,),X_groups_test.shape=[(1495, 10)],y_test.shape=(1495,)
[ 2018-07-31 22:11:04,114][cascade_classifier.fit_transform] group_dims=[10]
[ 2018-07-31 22:11:04,115][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:11:04,117][cascade_classifier.fit_transform] group_ends=[10]
[ 2018-07-31 22:11:04,118][cascade_classifier.fit_transform] X_train.shape=(3487, 10),X_test.shape=(1495, 10)
[ 2018-07-31 22:11:04,119][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(3487, 10), X_cur_test.shape=(1495, 10)
[ 2018-07-31 22:11:05,015][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=99.43%
[ 2018-07-31 22:11:06,193][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=99.14%
[ 2018-07-31 22:11:07,276][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 -

[ 2018-07-31 22:11:50,143][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=98.77%
[ 2018-07-31 22:11:50,144][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=98.73%
[ 2018-07-31 22:11:50,318][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=98.00%
[ 2018-07-31 22:11:50,524][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=97.71%
[ 2018-07-31 22:11:50,776][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=98.28%
[ 2018-07-31 22:11:50,987][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=98.28%
[ 2018-07-31 22:11:51,229][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=98.28%
[ 2018-07-31 22:11:51,485][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=97.99%
[ 

[ 2018-07-31 22:12:35,672][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=98.62%
[ 2018-07-31 22:12:35,673][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=98.46%
[ 2018-07-31 22:12:36,850][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=98.86%
[ 2018-07-31 22:12:38,260][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=98.29%
[ 2018-07-31 22:12:39,969][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=98.85%
[ 2018-07-31 22:12:41,413][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=99.14%
[ 2018-07-31 22:12:42,829][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=98.57%
[ 2018-07-31 22:12:44,428][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=98.28%
[ 

[ 2018-07-31 22:13:23,680][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=98.93%
[ 2018-07-31 22:13:23,684][cascade_classifier.fit_transform] [layer=5] look_indexs=[0], X_cur_train.shape=(3487, 16), X_cur_test.shape=(1495, 16)
[ 2018-07-31 22:13:24,885][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_0.predict)=98.29%
[ 2018-07-31 22:13:26,489][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_1.predict)=97.71%
[ 2018-07-31 22:13:28,101][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_2.predict)=98.85%
[ 2018-07-31 22:13:29,813][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_3.predict)=99.14%
[ 2018-07-31 22:13:32,295][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_4.predict)=98.28%
[ 2018-07-31 22:13:34,000][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_5.predict)

In [9]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 22:14:00,798][cascade_classifier.transform] X_groups_test.shape=[(1495, 10)]
[ 2018-07-31 22:14:00,806][cascade_classifier.transform] group_dims=[10]
[ 2018-07-31 22:14:00,808][cascade_classifier.transform] X_test.shape=(1495, 10)
[ 2018-07-31 22:14:00,810][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(1495, 10)
[ 2018-07-31 22:14:06,528][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(1495, 16)
[ 2018-07-31 22:14:12,479][cascade_classifier.transform] [layer=2] look_indexs=[0], X_cur_test.shape=(1495, 16)


Test Accuracy of GCForest = 98.795987 %


In [10]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '194.548', ' seconds')
[[1460    8]
 [  10   17]]


             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99      1468
        1.0       0.68      0.63      0.65        27

avg / total       0.99      0.99      0.99      1495



# Neural network 

In [11]:
# estimators 
# Evaluating the ANN
t0 = time()
# estimators 
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
3138/3138 [==============================] - 3s 1ms/step - loss: 0.3349 - acc: 0.9697
Epoch 2/50
3138/3138 [==============================] - 2s 608us/step - loss: 0.2437 - acc: 0.9780
Epoch 3/50
3138/3138 [==============================] - 2s 631us/step - loss: 0.2580 - acc: 0.9739
Epoch 4/50
3138/3138 [==============================] - 2s 534us/step - loss: 0.2426 - acc: 0.9793
Epoch 5/50
3138/3138 [==============================] - 2s 680us/step - loss: 0.2076 - acc: 0.9796
Epoch 6/50
3138/3138 [==============================] - 2s 565us/step - loss: 0.2382 - acc: 0.9812
Epoch 7/50
3138/3138 [==============================] - 2s 551us/step - loss: 0.2304 - acc: 0.9799
Epoch 8/50
3138/3138 [==============================] - 2s 679us/step - loss: 0.2174 - acc: 0.9802 1s - loss: 0.
Epoch 9/50
3138/3138 [==============================] - 2s 685us/step - loss: 0.2059 - acc: 0.9831
Epoch 10/50
3138/3138 [==============================] - 2s 696us/step - loss: 0.1414 - acc: 0.98

3138/3138 [==============================] - 2s 675us/step - loss: 0.1100 - acc: 0.9876
Epoch 33/50
3138/3138 [==============================] - 2s 589us/step - loss: 0.1223 - acc: 0.9866
Epoch 34/50
3138/3138 [==============================] - 2s 541us/step - loss: 0.1105 - acc: 0.9876
Epoch 35/50
3138/3138 [==============================] - 2s 646us/step - loss: 0.1976 - acc: 0.9822
Epoch 36/50
3138/3138 [==============================] - 2s 729us/step - loss: 0.1236 - acc: 0.9869
Epoch 37/50
3138/3138 [==============================] - 2s 786us/step - loss: 0.1637 - acc: 0.9863
Epoch 38/50
3138/3138 [==============================] - 2s 710us/step - loss: 0.1228 - acc: 0.9876
Epoch 39/50
3138/3138 [==============================] - 3s 811us/step - loss: 0.1072 - acc: 0.9873
Epoch 40/50
3138/3138 [==============================] - 2s 735us/step - loss: 0.1247 - acc: 0.9844
Epoch 41/50
3138/3138 [==============================] - 2s 680us/step - loss: 0.1271 - acc: 0.9866
Epoch 42/50


3138/3138 [==============================] - 2s 606us/step - loss: 0.1637 - acc: 0.9853
Epoch 12/50
3138/3138 [==============================] - 2s 646us/step - loss: 0.2006 - acc: 0.9831
Epoch 13/50
3138/3138 [==============================] - 2s 542us/step - loss: 0.1826 - acc: 0.9828
Epoch 14/50
3138/3138 [==============================] - 2s 686us/step - loss: 0.1447 - acc: 0.9844
Epoch 15/50
3138/3138 [==============================] - 2s 765us/step - loss: 0.1772 - acc: 0.9802
Epoch 16/50
3138/3138 [==============================] - 2s 662us/step - loss: 0.2254 - acc: 0.9818
Epoch 17/50
3138/3138 [==============================] - 2s 791us/step - loss: 0.1846 - acc: 0.9802
Epoch 18/50
3138/3138 [==============================] - 2s 758us/step - loss: 0.1583 - acc: 0.9786
Epoch 19/50
3138/3138 [==============================] - 2s 770us/step - loss: 0.1288 - acc: 0.9853
Epoch 20/50
3138/3138 [==============================] - 2s 544us/step - loss: 0.1120 - acc: 0.9882
Epoch 21/50


3138/3138 [==============================] - 2s 579us/step - loss: 0.2161 - acc: 0.9847
Epoch 43/50
3138/3138 [==============================] - 2s 544us/step - loss: 0.2158 - acc: 0.9853
Epoch 44/50
3138/3138 [==============================] - 2s 506us/step - loss: 0.2157 - acc: 0.9853
Epoch 45/50
3138/3138 [==============================] - 2s 516us/step - loss: 0.2161 - acc: 0.9850
Epoch 46/50
3138/3138 [==============================] - 2s 532us/step - loss: 0.2163 - acc: 0.9844
Epoch 47/50
3138/3138 [==============================] - 2s 606us/step - loss: 0.2183 - acc: 0.9841
Epoch 48/50
3138/3138 [==============================] - 2s 647us/step - loss: 0.2167 - acc: 0.9847 
Epoch 49/50
3138/3138 [==============================] - 2s 636us/step - loss: 0.2162 - acc: 0.9844 0s - loss: 0.2173 - acc: 0.98
Epoch 50/50
349/349 [==============================] - 0s 694us/step
Epoch 1/50
3138/3138 [==============================] - 5s 1ms/step - loss: 0.3270 - acc: 0.9710
Epoch 2/50
3138

3138/3138 [==============================] - 2s 623us/step - loss: 0.1259 - acc: 0.9869
Epoch 23/50
3138/3138 [==============================] - 2s 616us/step - loss: 0.1440 - acc: 0.9857
Epoch 24/50
3138/3138 [==============================] - 2s 628us/step - loss: 0.1351 - acc: 0.9853
Epoch 25/50
3138/3138 [==============================] - 2s 585us/step - loss: 0.1280 - acc: 0.9898 0s - loss: 0.1218 - acc: 0.
Epoch 26/50
3138/3138 [==============================] - 2s 642us/step - loss: 0.1248 - acc: 0.9885
Epoch 27/50
3138/3138 [==============================] - 2s 712us/step - loss: 0.1213 - acc: 0.9853
Epoch 28/50
3138/3138 [==============================] - 2s 698us/step - loss: 0.1094 - acc: 0.9888
Epoch 29/50
3138/3138 [==============================] - 2s 680us/step - loss: 0.1140 - acc: 0.9888
Epoch 30/50
3138/3138 [==============================] - 2s 722us/step - loss: 0.1077 - acc: 0.9888
Epoch 31/50
3138/3138 [==============================] - 2s 755us/step - loss: 0.103

3139/3139 [==============================] - 2s 633us/step - loss: 0.1648 - acc: 0.9815
Epoch 3/50
3139/3139 [==============================] - 2s 596us/step - loss: 0.2032 - acc: 0.9806
Epoch 4/50
3139/3139 [==============================] - 2s 623us/step - loss: 0.1420 - acc: 0.9863
Epoch 5/50
3139/3139 [==============================] - 2s 617us/step - loss: 0.1349 - acc: 0.9860
Epoch 6/50
3139/3139 [==============================] - 2s 627us/step - loss: 0.1839 - acc: 0.9828
Epoch 7/50
3139/3139 [==============================] - 2s 618us/step - loss: 0.1631 - acc: 0.9822
Epoch 8/50
3139/3139 [==============================] - 3s 803us/step - loss: 0.1456 - acc: 0.9876
Epoch 9/50
3139/3139 [==============================] - 2s 746us/step - loss: 0.1733 - acc: 0.9806
Epoch 10/50
3139/3139 [==============================] - 2s 695us/step - loss: 0.1305 - acc: 0.9863
Epoch 11/50
3139/3139 [==============================] - 2s 763us/step - loss: 0.1350 - acc: 0.9863
Epoch 12/50
3139/31

3139/3139 [==============================] - 2s 610us/step - loss: 0.1320 - acc: 0.9873
Epoch 34/50
3139/3139 [==============================] - 2s 605us/step - loss: 0.1334 - acc: 0.9882
Epoch 35/50
3139/3139 [==============================] - 2s 630us/step - loss: 0.1600 - acc: 0.9834
Epoch 36/50
3139/3139 [==============================] - 2s 639us/step - loss: 0.1538 - acc: 0.9869
Epoch 37/50
3139/3139 [==============================] - 2s 611us/step - loss: 0.1491 - acc: 0.9860
Epoch 38/50
3139/3139 [==============================] - 2s 632us/step - loss: 0.1337 - acc: 0.9882
Epoch 39/50
3139/3139 [==============================] - 2s 623us/step - loss: 0.1361 - acc: 0.9882
Epoch 40/50
3139/3139 [==============================] - 2s 632us/step - loss: 0.1348 - acc: 0.9873
Epoch 41/50
3139/3139 [==============================] - 2s 663us/step - loss: 0.1344 - acc: 0.9879
Epoch 42/50
3139/3139 [==============================] - 2s 531us/step - loss: 0.1482 - acc: 0.9847
Epoch 43/50


# DecisionTreeClassifier

In [12]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 98.327759 %
(' Time ', '0.113', ' seconds')
[[1454   14]
 [  11   16]]


             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99      1468
        1.0       0.53      0.59      0.56        27

avg / total       0.98      0.98      0.98      1495



# RandomForestClassifier

In [13]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 99.264214 %
(' Time ', '3.542', ' seconds')
[[1465    3]
 [   8   19]]


             precision    recall  f1-score   support

        0.0       0.99      1.00      1.00      1468
        1.0       0.86      0.70      0.78        27

avg / total       0.99      0.99      0.99      1495



# ExtraTreesClassifier

In [14]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 99.063545 %
(' Time ', '2.0', ' seconds')
[[1464    4]
 [  10   17]]


             precision    recall  f1-score   support

        0.0       0.99      1.00      1.00      1468
        1.0       0.81      0.63      0.71        27

avg / total       0.99      0.99      0.99      1495



# AdaBoostClassifier

In [15]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 98.795987 %
(' Time ', '1.482', ' seconds')
[[1463    5]
 [  13   14]]


             precision    recall  f1-score   support

        0.0       0.99      1.00      0.99      1468
        1.0       0.74      0.52      0.61        27

avg / total       0.99      0.99      0.99      1495



# Naive_bayes  GaussianNB

In [16]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 94.314381 %
(' Time ', '0.007', ' seconds')
[[1396   72]
 [  13   14]]


             precision    recall  f1-score   support

        0.0       0.99      0.95      0.97      1468
        1.0       0.16      0.52      0.25        27

avg / total       0.98      0.94      0.96      1495

