In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('Shuttle_withoutdupl_norm_v01.csv')

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

att1      att2     att3      att4      att5      att6      att7  \
0  0.214286  0.607955  0.12766  0.020145  0.207865  0.088428  0.347222   
1  0.085714  0.607955  0.12766  0.020145  0.207865  0.088428  0.458333   
2  0.200000  0.607955  0.12766  0.020145  0.067416  0.088428  0.361111   
3  0.085714  0.602273  0.12766  0.020145  0.207865  0.088428  0.472222   
4  0.185714  0.653409  0.12766  0.020145  0.067416  0.088428  0.375000   

       att8      att9  outlier  
0  0.746875  0.737113        1  
1  0.746875  0.716495        1  
2  0.912500  0.871134        1  
3  0.746875  0.716495        1  
4  0.912500  0.865979        1

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/Shuttle.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,9]
X = df[:,0:9]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0=time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:11:33,421][cascade_classifier.fit_transform] X_groups_train.shape=[(709, 9)],y_train.shape=(709,),X_groups_test.shape=[(304, 9)],y_test.shape=(304,)
[ 2018-07-31 22:11:33,422][cascade_classifier.fit_transform] group_dims=[9]
[ 2018-07-31 22:11:33,424][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:11:33,425][cascade_classifier.fit_transform] group_ends=[9]
[ 2018-07-31 22:11:33,427][cascade_classifier.fit_transform] X_train.shape=(709, 9),X_test.shape=(304, 9)
[ 2018-07-31 22:11:33,429][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(709, 9), X_cur_test.shape=(304, 9)
/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 8 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
[ 2018-07-31 22:11:34,252][kfold_wrapper.log_eval_metrics] Accuracy(la

[ 2018-07-31 22:12:17,128][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_7.predict)=100.00%
[ 2018-07-31 22:12:18,222][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_8.predict)=100.00%
[ 2018-07-31 22:12:19,391][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_9.predict)=100.00%
[ 2018-07-31 22:12:19,605][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=99.86%
[ 2018-07-31 22:12:19,606][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=100.00%
[ 2018-07-31 22:12:19,614][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=100.00%
[ 2018-07-31 22:12:19,620][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=100.00%
[ 2018-07-31 22:12:19,627][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=98.

[ 2018-07-31 22:12:55,889][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_7.predict)=100.00%
[ 2018-07-31 22:12:57,126][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_8.predict)=100.00%
[ 2018-07-31 22:12:58,406][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_9.predict)=100.00%
[ 2018-07-31 22:12:58,654][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=99.86%
[ 2018-07-31 22:12:58,656][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=100.00%
[ 2018-07-31 22:12:59,571][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=100.00%
[ 2018-07-31 22:13:00,829][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=100.00%
[ 2018-07-31 22:13:01,939][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=100

[ 2018-07-31 22:13:40,495][kfold_wrapper.log_eval_metrics] Accuracy(layer_4 - estimator_2 - 10_folds.train_cv.predict)=99.44%
[ 2018-07-31 22:13:40,496][kfold_wrapper.log_eval_metrics] Accuracy(layer_4 - estimator_2 - 10_folds.test.predict)=100.00%
[ 2018-07-31 22:13:40,501][cascade_classifier.calc_accuracy] Accuracy(layer_4 - train.classifier_average)=99.72%
[ 2018-07-31 22:13:40,502][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=100.00%
[ 2018-07-31 22:13:40,504][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=99.72%, accuracy_test=100.00%


In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 22:13:40,539][cascade_classifier.transform] X_groups_test.shape=[(304, 9)]
[ 2018-07-31 22:13:40,542][cascade_classifier.transform] group_dims=[9]
[ 2018-07-31 22:13:40,546][cascade_classifier.transform] X_test.shape=(304, 9)
[ 2018-07-31 22:13:40,550][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(304, 9)
[ 2018-07-31 22:13:47,396][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(304, 15)


Test Accuracy of GCForest = 100.000000 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '139.666', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
638/638 [==============================] - 1s 2ms/step - loss: 0.2459 - acc: 0.9875
Epoch 2/50
638/638 [==============================] - 0s 496us/step - loss: 0.0869 - acc: 0.9890
Epoch 3/50
638/638 [==============================] - 0s 526us/step - loss: 0.0614 - acc: 0.9890
Epoch 4/50
638/638 [==============================] - 0s 470us/step - loss: 0.0607 - acc: 0.9890
Epoch 5/50
638/638 [==============================] - 0s 483us/step - loss: 0.0594 - acc: 0.9890
Epoch 6/50
638/638 [==============================] - 0s 600us/step - loss: 0.0597 - acc: 0.9890
Epoch 7/50
638/638 [==============================] - 0s 594us/step - loss: 0.0612 - acc: 0.9890
Epoch 8/50
638/638 [==============================] - 0s 472us/step - loss: 0.0563 - acc: 0.9890
Epoch 9/50
638/638 [==============================] - 0s 481us/step - loss: 0.0557 - acc: 0.9890
Epoch 10/50
638/638 [==============================] - 0s 513us/step - loss: 0.0536 - acc: 0.9890
Epoch 11/50
638/638 [==========

638/638 [==============================] - 0s 505us/step - loss: 0.0327 - acc: 0.9937
Epoch 34/50
638/638 [==============================] - 0s 622us/step - loss: 0.0084 - acc: 0.9969
Epoch 35/50
638/638 [==============================] - 0s 617us/step - loss: 0.0059 - acc: 0.9984
Epoch 36/50
638/638 [==============================] - 0s 608us/step - loss: 0.0059 - acc: 0.9984 0s - loss: 0.0051 - acc: 1.
Epoch 37/50
638/638 [==============================] - 0s 526us/step - loss: 0.0050 - acc: 0.9984
Epoch 38/50
638/638 [==============================] - 0s 503us/step - loss: 0.0075 - acc: 0.9969
Epoch 39/50
638/638 [==============================] - 0s 555us/step - loss: 0.0038 - acc: 1.0000
Epoch 40/50
638/638 [==============================] - 0s 649us/step - loss: 0.0031 - acc: 1.0000
Epoch 41/50
638/638 [==============================] - 0s 518us/step - loss: 0.0025 - acc: 1.0000
Epoch 42/50
638/638 [==============================] - 0s 523us/step - loss: 0.0037 - acc: 0.9984
Epoc

638/638 [==============================] - 0s 627us/step - loss: 0.0363 - acc: 0.9922
Epoch 16/50
638/638 [==============================] - 0s 594us/step - loss: 0.0362 - acc: 0.9922
Epoch 17/50
638/638 [==============================] - 0s 559us/step - loss: 0.0351 - acc: 0.9922
Epoch 18/50
638/638 [==============================] - 0s 496us/step - loss: 0.0355 - acc: 0.9922
Epoch 19/50
638/638 [==============================] - 0s 501us/step - loss: 0.0333 - acc: 0.9922
Epoch 20/50
638/638 [==============================] - 0s 615us/step - loss: 0.0321 - acc: 0.9922
Epoch 21/50
638/638 [==============================] - 0s 777us/step - loss: 0.0312 - acc: 0.9922
Epoch 22/50
638/638 [==============================] - 0s 704us/step - loss: 0.0328 - acc: 0.9922
Epoch 23/50
638/638 [==============================] - 0s 611us/step - loss: 0.0302 - acc: 0.9922
Epoch 24/50
638/638 [==============================] - 0s 569us/step - loss: 0.0263 - acc: 0.9922
Epoch 25/50
638/638 [===========

638/638 [==============================] - 0s 759us/step - loss: 0.0024 - acc: 0.9984
Epoch 49/50
638/638 [==============================] - 0s 772us/step - loss: 0.0027 - acc: 1.0000
Epoch 50/50
71/71 [==============================] - 1s 9ms/step
Epoch 1/50
638/638 [==============================] - 4s 5ms/step - loss: 0.2460 - acc: 0.9875
Epoch 2/50
638/638 [==============================] - 0s 594us/step - loss: 0.0890 - acc: 0.9875
Epoch 3/50
638/638 [==============================] - 0s 545us/step - loss: 0.0688 - acc: 0.9875
Epoch 4/50
638/638 [==============================] - 0s 589us/step - loss: 0.0678 - acc: 0.9875
Epoch 5/50
638/638 [==============================] - 0s 693us/step - loss: 0.0667 - acc: 0.9875
Epoch 6/50
638/638 [==============================] - 0s 703us/step - loss: 0.0658 - acc: 0.9875
Epoch 7/50
638/638 [==============================] - 0s 550us/step - loss: 0.0641 - acc: 0.9875
Epoch 8/50
638/638 [==============================] - 0s 617us/step - loss

638/638 [==============================] - 0s 677us/step - loss: 0.0352 - acc: 0.9906
Epoch 31/50
638/638 [==============================] - 0s 744us/step - loss: 0.0249 - acc: 0.9922
Epoch 32/50
638/638 [==============================] - 1s 851us/step - loss: 0.0166 - acc: 0.9969
Epoch 33/50
638/638 [==============================] - 0s 741us/step - loss: 0.0156 - acc: 0.9937
Epoch 34/50
638/638 [==============================] - 1s 942us/step - loss: 0.0114 - acc: 0.9969
Epoch 35/50
638/638 [==============================] - 1s 810us/step - loss: 0.0120 - acc: 0.9969
Epoch 36/50
638/638 [==============================] - 0s 701us/step - loss: 0.0096 - acc: 0.9969
Epoch 37/50
638/638 [==============================] - 0s 752us/step - loss: 0.0072 - acc: 1.0000
Epoch 38/50
638/638 [==============================] - 1s 830us/step - loss: 0.0059 - acc: 1.0000
Epoch 39/50
638/638 [==============================] - 0s 702us/step - loss: 0.0165 - acc: 0.9953
Epoch 40/50
638/638 [===========

638/638 [==============================] - 0s 753us/step - loss: 0.0555 - acc: 0.9875
Epoch 13/50
638/638 [==============================] - 1s 851us/step - loss: 0.0540 - acc: 0.9875
Epoch 14/50
638/638 [==============================] - 0s 714us/step - loss: 0.0510 - acc: 0.9875
Epoch 15/50
638/638 [==============================] - 1s 850us/step - loss: 0.0508 - acc: 0.9875
Epoch 16/50
638/638 [==============================] - 1s 809us/step - loss: 0.0504 - acc: 0.9875
Epoch 17/50
638/638 [==============================] - 1s 785us/step - loss: 0.0452 - acc: 0.9875
Epoch 18/50
638/638 [==============================] - 1s 803us/step - loss: 0.0450 - acc: 0.9875
Epoch 19/50
638/638 [==============================] - 1s 856us/step - loss: 0.0414 - acc: 0.9875
Epoch 20/50
638/638 [==============================] - 0s 680us/step - loss: 0.0370 - acc: 0.9875
Epoch 21/50
638/638 [==============================] - 0s 624us/step - loss: 0.0376 - acc: 0.9875
Epoch 22/50
638/638 [===========

639/639 [==============================] - 1s 891us/step - loss: 0.0060 - acc: 0.9984
Epoch 45/50
639/639 [==============================] - 1s 881us/step - loss: 0.0026 - acc: 1.0000
Epoch 46/50
639/639 [==============================] - 0s 755us/step - loss: 0.0026 - acc: 0.9984
Epoch 47/50
639/639 [==============================] - 1s 930us/step - loss: 0.0022 - acc: 1.0000
Epoch 48/50
639/639 [==============================] - 1s 824us/step - loss: 0.0017 - acc: 1.0000
Epoch 49/50
639/639 [==============================] - 1s 946us/step - loss: 0.0012 - acc: 1.0000
Epoch 50/50
70/70 [==============================] - 1s 11ms/step
Accuracy mean: 0.998591549296
Accuracy variance: 0.00422535211268
(' Time ', '294.841', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 100.000000 %
(' Time ', '0.004', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 100.000000 %
(' Time ', '1.628', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 100.000000 %
(' Time ', '2.808', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 100.000000 %
(' Time ', '0.049', ' seconds')
[[299   0]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       299
        1.0       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00       304



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 82.565789 %
(' Time ', '0.052', ' seconds')
[[246  53]
 [  0   5]]


             precision    recall  f1-score   support

        0.0       1.00      0.82      0.90       299
        1.0       0.09      1.00      0.16         5

avg / total       0.98      0.83      0.89       304

