In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('Wilt_withoutdupl_norm_05.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

GLCM_pan  Mean_Green  Mean_Red  Mean_NIR    SD_pan  outlier
0  0.656711    0.050984  0.044570  0.218476  0.132110        1
1  0.680591    0.049425  0.041939  0.177275  0.106749        1
2  0.734892    0.047396  0.042926  0.259034  0.143741        1
3  0.698087    0.035317  0.027066  0.127065  0.095697        1
4  0.738927    0.046076  0.040228  0.295501  0.112481        1

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/Wilt.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,5]
X = df[:,0:5]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0=time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:12:13,706][cascade_classifier.fit_transform] X_groups_train.shape=[(3373, 5)],y_train.shape=(3373,),X_groups_test.shape=[(1446, 5)],y_test.shape=(1446,)
[ 2018-07-31 22:12:13,708][cascade_classifier.fit_transform] group_dims=[5]
[ 2018-07-31 22:12:13,709][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:12:13,725][cascade_classifier.fit_transform] group_ends=[5]
[ 2018-07-31 22:12:13,726][cascade_classifier.fit_transform] X_train.shape=(3373, 5),X_test.shape=(1446, 5)
[ 2018-07-31 22:12:13,729][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(3373, 5), X_cur_test.shape=(1446, 5)
[ 2018-07-31 22:12:15,032][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=98.52%
[ 2018-07-31 22:12:16,673][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=98.22%
[ 2018-07-31 22:12:17,881][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_fold

[ 2018-07-31 22:13:08,378][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=98.70%
[ 2018-07-31 22:13:08,381][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=98.34%
[ 2018-07-31 22:13:08,411][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=98.82%
[ 2018-07-31 22:13:08,446][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=98.52%
[ 2018-07-31 22:13:08,493][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=99.11%
[ 2018-07-31 22:13:08,529][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=98.82%
[ 2018-07-31 22:13:08,547][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=97.93%
[ 2018-07-31 22:13:08,564][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=98.52%
[ 

[ 2018-07-31 22:13:55,568][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=98.52%
[ 2018-07-31 22:13:55,570][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=98.34%
[ 2018-07-31 22:13:56,784][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=98.82%
[ 2018-07-31 22:13:58,329][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=98.22%
[ 2018-07-31 22:14:00,006][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=97.93%
[ 2018-07-31 22:14:02,088][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=97.93%
[ 2018-07-31 22:14:04,118][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=98.52%
[ 2018-07-31 22:14:05,941][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=98.22%
[ 

[ 2018-07-31 22:15:00,714][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=98.27%
[ 2018-07-31 22:15:00,715][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=98.67%, accuracy_test=98.20%


In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 22:15:00,802][cascade_classifier.transform] X_groups_test.shape=[(1446, 5)]
[ 2018-07-31 22:15:00,812][cascade_classifier.transform] group_dims=[5]
[ 2018-07-31 22:15:00,817][cascade_classifier.transform] X_test.shape=(1446, 5)
[ 2018-07-31 22:15:00,822][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(1446, 5)
[ 2018-07-31 22:15:08,102][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(1446, 11)


Test Accuracy of GCForest = 98.201936 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '185.157', ' seconds')
[[1356    9]
 [  17   64]]


             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99      1365
        1.0       0.88      0.79      0.83        81

avg / total       0.98      0.98      0.98      1446



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
3035/3035 [==============================] - 5s 2ms/step - loss: 0.2521 - acc: 0.9394A: 4s - lo
Epoch 2/50
3035/3035 [==============================] - 3s 860us/step - loss: 0.1954 - acc: 0.9486
Epoch 3/50
3035/3035 [==============================] - 3s 835us/step - loss: 0.1943 - acc: 0.9486
Epoch 4/50
3035/3035 [==============================] - 3s 890us/step - loss: 0.1908 - acc: 0.9486
Epoch 5/50
3035/3035 [==============================] - 2s 807us/step - loss: 0.1913 - acc: 0.9486
Epoch 6/50
3035/3035 [==============================] - 2s 741us/step - loss: 0.1871 - acc: 0.9486
Epoch 7/50
3035/3035 [==============================] - 2s 785us/step - loss: 0.1882 - acc: 0.9486
Epoch 8/50
3035/3035 [==============================] - 2s 728us/step - loss: 0.1826 - acc: 0.9486
Epoch 9/50
3035/3035 [==============================] - 2s 697us/step - loss: 0.1748 - acc: 0.9486
Epoch 10/50
3035/3035 [==============================] - 2s 713us/step - loss: 0.1682 - acc: 0.9486
E

3035/3035 [==============================] - 3s 855us/step - loss: 0.0488 - acc: 0.9848
Epoch 32/50
3035/3035 [==============================] - 2s 795us/step - loss: 0.0462 - acc: 0.9858
Epoch 33/50
3035/3035 [==============================] - 2s 813us/step - loss: 0.0338 - acc: 0.9901
Epoch 34/50
3035/3035 [==============================] - 3s 839us/step - loss: 0.0717 - acc: 0.9802
Epoch 35/50
3035/3035 [==============================] - 2s 784us/step - loss: 0.0564 - acc: 0.9815
Epoch 36/50
3035/3035 [==============================] - 2s 750us/step - loss: 0.0364 - acc: 0.9871
Epoch 37/50
3035/3035 [==============================] - 2s 697us/step - loss: 0.0331 - acc: 0.9908
Epoch 38/50
3035/3035 [==============================] - 2s 645us/step - loss: 0.0339 - acc: 0.9878
Epoch 39/50
3035/3035 [==============================] - 2s 605us/step - loss: 0.0392 - acc: 0.9855
Epoch 40/50
3035/3035 [==============================] - 2s 575us/step - loss: 0.0573 - acc: 0.9829
Epoch 41/50


3036/3036 [==============================] - 2s 599us/step - loss: 0.1476 - acc: 0.9499 1s -
Epoch 12/50
3036/3036 [==============================] - 2s 662us/step - loss: 0.1292 - acc: 0.9499
Epoch 13/50
3036/3036 [==============================] - 2s 619us/step - loss: 0.1202 - acc: 0.9529
Epoch 14/50
3036/3036 [==============================] - 2s 624us/step - loss: 0.0991 - acc: 0.9634
Epoch 15/50
3036/3036 [==============================] - 2s 663us/step - loss: 0.0819 - acc: 0.9704
Epoch 16/50
3036/3036 [==============================] - 2s 665us/step - loss: 0.0798 - acc: 0.9740
Epoch 17/50
3036/3036 [==============================] - 2s 798us/step - loss: 0.0818 - acc: 0.9740
Epoch 18/50
3036/3036 [==============================] - 2s 751us/step - loss: 0.0779 - acc: 0.9746
Epoch 19/50
3036/3036 [==============================] - 2s 735us/step - loss: 0.0491 - acc: 0.9848
Epoch 20/50
3036/3036 [==============================] - 2s 734us/step - loss: 0.0467 - acc: 0.9862
Epoch 2

3036/3036 [==============================] - 2s 754us/step - loss: 0.0317 - acc: 0.9901 2
Epoch 42/50
3036/3036 [==============================] - 2s 762us/step - loss: 0.0478 - acc: 0.9822
Epoch 43/50
3036/3036 [==============================] - 2s 740us/step - loss: 0.0414 - acc: 0.9862
Epoch 44/50
3036/3036 [==============================] - 2s 625us/step - loss: 0.0347 - acc: 0.9872
Epoch 45/50
3036/3036 [==============================] - 2s 731us/step - loss: 0.0354 - acc: 0.9885
Epoch 46/50
3036/3036 [==============================] - 2s 711us/step - loss: 0.0409 - acc: 0.9878 0s - loss: 0.0412 - acc: 0.98
Epoch 47/50
3036/3036 [==============================] - 2s 780us/step - loss: 0.0337 - acc: 0.9881 2s - loss: 0.0199 - ac - ETA: 1s - lo
Epoch 48/50
3036/3036 [==============================] - 2s 719us/step - loss: 0.0303 - acc: 0.9878
Epoch 49/50
3036/3036 [==============================] - 2s 751us/step - loss: 0.0351 - acc: 0.9891
Epoch 50/50
337/337 [=====================

3036/3036 [==============================] - 2s 810us/step - loss: 0.0479 - acc: 0.9839
Epoch 21/50
3036/3036 [==============================] - 2s 767us/step - loss: 0.0750 - acc: 0.9753
Epoch 22/50
3036/3036 [==============================] - 2s 779us/step - loss: 0.0462 - acc: 0.9855
Epoch 23/50
3036/3036 [==============================] - 2s 733us/step - loss: 0.0375 - acc: 0.9878
Epoch 24/50
3036/3036 [==============================] - 2s 630us/step - loss: 0.0477 - acc: 0.9839
Epoch 25/50
3036/3036 [==============================] - 2s 599us/step - loss: 0.0394 - acc: 0.9865
Epoch 26/50
3036/3036 [==============================] - 2s 631us/step - loss: 0.0476 - acc: 0.9842
Epoch 27/50
3036/3036 [==============================] - 2s 531us/step - loss: 0.0505 - acc: 0.9809
Epoch 28/50
3036/3036 [==============================] - 2s 590us/step - loss: 0.0517 - acc: 0.9812
Epoch 29/50
3036/3036 [==============================] - 2s 561us/step - loss: 0.0492 - acc: 0.9852
Epoch 30/50


337/337 [==============================] - 0s 1ms/step
Epoch 1/50
3036/3036 [==============================] - 5s 2ms/step - loss: 0.2404 - acc: 0.9394
Epoch 2/50
3036/3036 [==============================] - 2s 651us/step - loss: 0.1930 - acc: 0.9499 1
Epoch 3/50
3036/3036 [==============================] - 2s 692us/step - loss: 0.1884 - acc: 0.9499
Epoch 4/50
3036/3036 [==============================] - 2s 677us/step - loss: 0.1887 - acc: 0.9499
Epoch 5/50
3036/3036 [==============================] - 2s 593us/step - loss: 0.1832 - acc: 0.9499
Epoch 6/50
3036/3036 [==============================] - 2s 623us/step - loss: 0.1820 - acc: 0.9499
Epoch 7/50
3036/3036 [==============================] - 2s 684us/step - loss: 0.1786 - acc: 0.9499
Epoch 8/50
3036/3036 [==============================] - 2s 718us/step - loss: 0.1776 - acc: 0.9499
Epoch 9/50
3036/3036 [==============================] - 2s 623us/step - loss: 0.1684 - acc: 0.9499
Epoch 10/50
3036/3036 [==============================]

3036/3036 [==============================] - 2s 633us/step - loss: 0.0446 - acc: 0.9852
Epoch 31/50
3036/3036 [==============================] - 2s 597us/step - loss: 0.0365 - acc: 0.9881
Epoch 32/50
3036/3036 [==============================] - 2s 528us/step - loss: 0.0434 - acc: 0.9868
Epoch 33/50
3036/3036 [==============================] - 1s 478us/step - loss: 0.0323 - acc: 0.9901
Epoch 34/50
3036/3036 [==============================] - 2s 514us/step - loss: 0.0318 - acc: 0.9855
Epoch 35/50
3036/3036 [==============================] - 1s 478us/step - loss: 0.0422 - acc: 0.9852
Epoch 36/50
3036/3036 [==============================] - 1s 480us/step - loss: 0.0357 - acc: 0.9865
Epoch 37/50
3036/3036 [==============================] - 2s 499us/step - loss: 0.0344 - acc: 0.9872
Epoch 38/50
3036/3036 [==============================] - 2s 508us/step - loss: 0.0403 - acc: 0.9875
Epoch 39/50
3036/3036 [==============================] - 2s 560us/step - loss: 0.0308 - acc: 0.9901
Epoch 40/50


# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 96.680498 %
(' Time ', '0.028', ' seconds')
[[1348   17]
 [  31   50]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.98      1365
        1.0       0.75      0.62      0.68        81

avg / total       0.96      0.97      0.97      1446



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 97.233748 %
(' Time ', '2.084', ' seconds')
[[1358    7]
 [  33   48]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.99      1365
        1.0       0.87      0.59      0.71        81

avg / total       0.97      0.97      0.97      1446



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 97.579530 %
(' Time ', '0.923', ' seconds')
[[1362    3]
 [  32   49]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99      1365
        1.0       0.94      0.60      0.74        81

avg / total       0.98      0.98      0.97      1446



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 97.510373 %
(' Time ', '0.889', ' seconds')
[[1357    8]
 [  28   53]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.99      1365
        1.0       0.87      0.65      0.75        81

avg / total       0.97      0.98      0.97      1446



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 90.525588 %
(' Time ', '0.006', ' seconds')
[[1265  100]
 [  37   44]]


             precision    recall  f1-score   support

        0.0       0.97      0.93      0.95      1365
        1.0       0.31      0.54      0.39        81

avg / total       0.93      0.91      0.92      1446

