In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('MAGIC Gamma Telescope Data.csv')  

df['Class'] = df.Class.apply(lambda label: 1 if label == "g" else 0)


df.head()

Flength    Fwidth   Fsize   Fconc  Fconc1     Fasym  Fm3long  Fm3trans  \
0   28.7967   16.0021  2.6449  0.3918  0.1982   27.7004  22.0110   -8.2027   
1   31.6036   11.7235  2.5185  0.5303  0.3773   26.2722  23.8238   -9.9574   
2  162.0520  136.0310  4.0612  0.0374  0.0187  116.7410 -64.8580  -45.2160   
3   23.8172    9.5728  2.3385  0.6147  0.3922   27.2107  -6.4633   -7.1513   
4   75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277  28.5525   21.8393   

    Falpha     Fdist  Class  
0  40.0920   81.8828      1  
1   6.3609  205.2610      1  
2  76.9600  256.7880      1  
3  10.4490  116.7370      1  
4   4.6480  356.4620      1

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/aloi.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,10]
X = df[:,0:10]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/kader/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2019-01-12 18:20:57,057][cascade_classifier.fit_transform] X_groups_train.shape=[(13314, 10)],y_train.shape=(13314,),X_groups_test.shape=[(5706, 10)],y_test.shape=(5706,)
[ 2019-01-12 18:20:57,059][cascade_classifier.fit_transform] group_dims=[10]
[ 2019-01-12 18:20:57,061][cascade_classifier.fit_transform] group_starts=[0]
[ 2019-01-12 18:20:57,063][cascade_classifier.fit_transform] group_ends=[10]
[ 2019-01-12 18:20:57,064][cascade_classifier.fit_transform] X_train.shape=(13314, 10),X_test.shape=(5706, 10)
[ 2019-01-12 18:20:57,068][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(13314, 10), X_cur_test.shape=(5706, 10)
[ 2019-01-12 18:20:59,650][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=88.97%
[ 2019-01-12 18:21:02,225][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=87.09%
[ 2019-01-12 18:21:04,966][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator

[ 2019-01-12 18:22:08,545][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=87.49%
[ 2019-01-12 18:22:08,547][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=88.36%
[ 2019-01-12 18:22:08,792][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=85.97%
[ 2019-01-12 18:22:09,029][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=88.29%
[ 2019-01-12 18:22:09,277][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=88.74%
[ 2019-01-12 18:22:09,611][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=88.20%
[ 2019-01-12 18:22:09,863][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=87.08%
[ 2019-01-12 18:22:10,108][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=86.63%
[ 

[ 2019-01-12 18:23:11,859][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=87.66%
[ 2019-01-12 18:23:11,862][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=88.42%
[ 2019-01-12 18:23:12,898][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=87.47%
[ 2019-01-12 18:23:14,057][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=87.99%
[ 2019-01-12 18:23:15,216][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=86.64%
[ 2019-01-12 18:23:16,383][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=87.68%
[ 2019-01-12 18:23:17,619][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=87.00%
[ 2019-01-12 18:23:18,741][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=88.35%
[ 

[ 2019-01-12 18:24:03,739][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=88.36%
[ 2019-01-12 18:24:03,740][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=88.01%, accuracy_test=88.47%


In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

[ 2019-01-12 18:24:03,791][cascade_classifier.transform] X_groups_test.shape=[(5706, 10)]
[ 2019-01-12 18:24:03,794][cascade_classifier.transform] group_dims=[10]
[ 2019-01-12 18:24:03,802][cascade_classifier.transform] X_test.shape=(5706, 10)
[ 2019-01-12 18:24:03,811][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(5706, 10)
[ 2019-01-12 18:24:06,261][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(5706, 16)


Test Accuracy of GCForest = 88.468279 %
(' Time ', '191.519', ' seconds')


In [9]:
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

[[1566  451]
 [ 207 3482]]


             precision    recall  f1-score   support

        0.0       0.88      0.78      0.83      2017
        1.0       0.89      0.94      0.91      3689

avg / total       0.88      0.88      0.88      5706



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

Using TensorFlow backend.


Epoch 1/50
11982/11982 [==============================] - 7s 563us/step - loss: 0.5836 - acc: 0.7458
Epoch 2/50
11982/11982 [==============================] - 6s 487us/step - loss: 0.4496 - acc: 0.7919
Epoch 3/50
11982/11982 [==============================] - 6s 475us/step - loss: 0.4247 - acc: 0.8093
Epoch 4/50
11982/11982 [==============================] - 6s 481us/step - loss: 0.4096 - acc: 0.8146
Epoch 5/50
11982/11982 [==============================] - 6s 480us/step - loss: 0.4085 - acc: 0.8159
Epoch 6/50
11982/11982 [==============================] - 6s 476us/step - loss: 0.4015 - acc: 0.8180
Epoch 7/50
11982/11982 [==============================] - 6s 481us/step - loss: 0.3955 - acc: 0.8252
Epoch 8/50
11982/11982 [==============================] - 6s 477us/step - loss: 0.3968 - acc: 0.8196
Epoch 9/50
11982/11982 [==============================] - 6s 478us/step - loss: 0.3894 - acc: 0.8257
Epoch 10/50
11982/11982 [==============================] - 6s 479us/step - loss: 0.3831 - a

11982/11982 [==============================] - 6s 470us/step - loss: 0.3365 - acc: 0.8527
Epoch 31/50
11982/11982 [==============================] - 6s 482us/step - loss: 0.3328 - acc: 0.8544
Epoch 32/50
11982/11982 [==============================] - 6s 496us/step - loss: 0.3307 - acc: 0.8543
Epoch 33/50
11982/11982 [==============================] - 7s 567us/step - loss: 0.3272 - acc: 0.8577
Epoch 34/50
11982/11982 [==============================] - 6s 497us/step - loss: 0.3281 - acc: 0.8579
Epoch 35/50
11982/11982 [==============================] - 7s 543us/step - loss: 0.3235 - acc: 0.8595
Epoch 36/50
11982/11982 [==============================] - 6s 476us/step - loss: 0.3206 - acc: 0.8574
Epoch 37/50
11982/11982 [==============================] - 6s 496us/step - loss: 0.3218 - acc: 0.8593
Epoch 38/50
11982/11982 [==============================] - 7s 553us/step - loss: 0.3200 - acc: 0.8592
Epoch 39/50
11982/11982 [==============================] - 6s 483us/step - loss: 0.3148 - acc:

11982/11982 [==============================] - 7s 588us/step - loss: 0.3902 - acc: 0.8272
Epoch 10/50
11982/11982 [==============================] - 8s 657us/step - loss: 0.3899 - acc: 0.8236
Epoch 11/50
11982/11982 [==============================] - 7s 547us/step - loss: 0.3863 - acc: 0.8282
Epoch 12/50
11982/11982 [==============================] - 7s 553us/step - loss: 0.3838 - acc: 0.8278
Epoch 13/50
11982/11982 [==============================] - 7s 613us/step - loss: 0.3777 - acc: 0.8294
Epoch 14/50
11982/11982 [==============================] - 6s 522us/step - loss: 0.3753 - acc: 0.8305
Epoch 15/50
11982/11982 [==============================] - 6s 489us/step - loss: 0.3722 - acc: 0.8345
Epoch 16/50
11982/11982 [==============================] - 7s 618us/step - loss: 0.3701 - acc: 0.8350
Epoch 17/50
11982/11982 [==============================] - 6s 542us/step - loss: 0.3684 - acc: 0.8368
Epoch 18/50
11982/11982 [==============================] - 6s 478us/step - loss: 0.3628 - acc:

11983/11983 [==============================] - 6s 505us/step - loss: 0.3208 - acc: 0.8599
Epoch 39/50
11983/11983 [==============================] - 5s 439us/step - loss: 0.3175 - acc: 0.8611
Epoch 40/50
11983/11983 [==============================] - 5s 439us/step - loss: 0.3149 - acc: 0.8592
Epoch 41/50
11983/11983 [==============================] - 5s 448us/step - loss: 0.3146 - acc: 0.8610
Epoch 42/50
11983/11983 [==============================] - 5s 442us/step - loss: 0.3112 - acc: 0.8635
Epoch 43/50
11983/11983 [==============================] - 6s 502us/step - loss: 0.3081 - acc: 0.8666
Epoch 44/50
11983/11983 [==============================] - ETA: 0s - loss: 0.3085 - acc: 0.864 - 6s 466us/step - loss: 0.3086 - acc: 0.8643
Epoch 45/50
11983/11983 [==============================] - 6s 467us/step - loss: 0.3042 - acc: 0.8676
Epoch 46/50
11983/11983 [==============================] - 6s 473us/step - loss: 0.3035 - acc: 0.8676
Epoch 47/50
11983/11983 [==============================]

11983/11983 [==============================] - 8s 637us/step - loss: 0.3674 - acc: 0.8368
Epoch 17/50
11983/11983 [==============================] - 7s 558us/step - loss: 0.3634 - acc: 0.8370
Epoch 18/50
11983/11983 [==============================] - 5s 450us/step - loss: 0.3631 - acc: 0.8366
Epoch 19/50
11983/11983 [==============================] - 5s 437us/step - loss: 0.3599 - acc: 0.8389
Epoch 20/50
11983/11983 [==============================] - 6s 480us/step - loss: 0.3586 - acc: 0.8427
Epoch 21/50
11983/11983 [==============================] - 7s 623us/step - loss: 0.3563 - acc: 0.8413
Epoch 22/50
11983/11983 [==============================] - 7s 584us/step - loss: 0.3541 - acc: 0.8413
Epoch 23/50
11983/11983 [==============================] - 6s 525us/step - loss: 0.3505 - acc: 0.8448
Epoch 24/50
11983/11983 [==============================] - 6s 500us/step - loss: 0.3455 - acc: 0.8470
Epoch 25/50
11983/11983 [==============================] - 5s 458us/step - loss: 0.3423 - acc:

11983/11983 [==============================] - 6s 528us/step - loss: 0.3060 - acc: 0.8645
Epoch 45/50
11983/11983 [==============================] - 7s 622us/step - loss: 0.3017 - acc: 0.8671
Epoch 46/50
11983/11983 [==============================] - 7s 552us/step - loss: 0.2956 - acc: 0.8684
Epoch 47/50
11983/11983 [==============================] - 7s 565us/step - loss: 0.2983 - acc: 0.8696
Epoch 48/50
11983/11983 [==============================] - 8s 638us/step - loss: 0.2929 - acc: 0.8688
Epoch 49/50
11983/11983 [==============================] - 8s 627us/step - loss: 0.2943 - acc: 0.8707 0s - loss: 0.2937 - acc: 0.
Epoch 50/50
1331/1331 [==============================] - 0s 195us/step
Epoch 1/50
11983/11983 [==============================] - 7s 617us/step - loss: 0.6273 - acc: 0.7481
Epoch 2/50
11983/11983 [==============================] - 8s 658us/step - loss: 0.4558 - acc: 0.7915
Epoch 3/50
11983/11983 [==============================] - 7s 562us/step - loss: 0.4298 - acc: 0.805

11983/11983 [==============================] - 6s 495us/step - loss: 0.3481 - acc: 0.8456
Epoch 24/50
11983/11983 [==============================] - 6s 500us/step - loss: 0.3494 - acc: 0.8439
Epoch 25/50
11983/11983 [==============================] - 6s 473us/step - loss: 0.3460 - acc: 0.8502
Epoch 26/50
11983/11983 [==============================] - 6s 484us/step - loss: 0.3441 - acc: 0.8485
Epoch 27/50
11983/11983 [==============================] - 6s 470us/step - loss: 0.3419 - acc: 0.8498
Epoch 28/50
11983/11983 [==============================] - 5s 431us/step - loss: 0.3355 - acc: 0.8520
Epoch 29/50
11983/11983 [==============================] - 5s 421us/step - loss: 0.3354 - acc: 0.8536
Epoch 30/50
11983/11983 [==============================] - 6s 472us/step - loss: 0.3330 - acc: 0.8515
Epoch 31/50
11983/11983 [==============================] - 9s 778us/step - loss: 0.3308 - acc: 0.8557
Epoch 32/50
11983/11983 [==============================] - 7s 557us/step - loss: 0.3301 - acc:

In [11]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '3141.778', ' seconds')
[[1566  451]
 [ 207 3482]]


             precision    recall  f1-score   support

        0.0       0.88      0.78      0.83      2017
        1.0       0.89      0.94      0.91      3689

avg / total       0.88      0.88      0.88      5706



# DecisionTreeClassifier

In [12]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of DecisionTreeClassifier = 81.090081 %
[[1471  546]
 [ 533 3156]]


             precision    recall  f1-score   support

        0.0       0.73      0.73      0.73      2017
        1.0       0.85      0.86      0.85      3689

avg / total       0.81      0.81      0.81      5706

(' Time ', '0.295', ' seconds')


# RandomForestClassifier

In [13]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of RandomForestClassifier = 88.135296 %
[[1560  457]
 [ 220 3469]]


             precision    recall  f1-score   support

        0.0       0.88      0.77      0.82      2017
        1.0       0.88      0.94      0.91      3689

avg / total       0.88      0.88      0.88      5706

(' Time ', '5.354', ' seconds')


# ExtraTreesClassifier

In [14]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of ExtraTreesClassifier = 87.644585 %
[[1500  517]
 [ 188 3501]]


             precision    recall  f1-score   support

        0.0       0.89      0.74      0.81      2017
        1.0       0.87      0.95      0.91      3689

avg / total       0.88      0.88      0.87      5706

(' Time ', '1.661', ' seconds')


# AdaBoostClassifier

In [15]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of AdaBoostClassifier = 84.086926 %
[[1442  575]
 [ 333 3356]]


             precision    recall  f1-score   support

        0.0       0.81      0.71      0.76      2017
        1.0       0.85      0.91      0.88      3689

avg / total       0.84      0.84      0.84      5706

(' Time ', '2.65', ' seconds')


# Naive_bayes  GaussianNB

In [16]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")

Test Accuracy of GaussianNB = 72.450053 %
[[ 741 1276]
 [ 296 3393]]


             precision    recall  f1-score   support

        0.0       0.71      0.37      0.49      2017
        1.0       0.73      0.92      0.81      3689

avg / total       0.72      0.72      0.70      5706

(' Time ', '0.169', ' seconds')
