In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
 
df=pd.read_csv('Waveform_withoutdupl_norm_v01.csv')  
del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)
df.head()

att1      att2      att3      att4      att5      att6      att7  \
0  0.323657  0.793785  0.848661  0.660063  0.622244  0.755102  0.760762   
1  0.423803  0.769774  0.632130  0.572471  0.747495  0.670408  0.715232   
2  0.477504  0.580508  0.554133  0.476538  0.851703  0.509184  0.745861   
3  0.645864  0.570621  0.525029  0.631908  0.682365  0.382653  0.478477   
4  0.219158  0.690678  0.530850  0.715328  0.687375  0.571429  0.649007   

       att8      att9     att10   ...        att13     att14     att15  \
0  0.671655  0.603723  0.636170   ...     0.281899  0.203557  0.286607   
1  0.617958  0.637411  0.457447   ...     0.302671  0.375494  0.296429   
2  0.785211  0.508865  0.519149   ...     0.341246  0.384387  0.229464   
3  0.608275  0.476950  0.190426   ...     0.500495  0.555336  0.463393   
4  0.562500  0.523050  0.303191   ...     0.190900  0.408103  0.322321   

      att16     att17     att18     att19     att20     att21  outlier  
0  0.474383  0.352483  0.358857  0.275626  0.465937  0.220884        1  
1  0.383302  0.545278  0.394286  0.451025  0.470803  0.468541        1  
2  0.350095  0.117819  0.406857  0.149203  0.402676  0.370817        1  
3  0.537951  0.564752  0.485714  0.576310  0.518248  0.597055        1  
4  0.425996  0.400195  0.701714  0.515945  0.294404  0.463186        1  

[5 rows x 22 columns]

In [3]:
df.shape

(3443, 22)

In [4]:
# df to values
df = df.values

In [5]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/waveform.json")   
gc = GCForest(config)

In [6]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,21]
X = df[:,0:21]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
# number of class
len(np.unique(y_train))

2

In [8]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:12:00,193][cascade_classifier.fit_transform] X_groups_train.shape=[(2410, 21)],y_train.shape=(2410,),X_groups_test.shape=[(1033, 21)],y_test.shape=(1033,)
[ 2018-07-31 22:12:00,196][cascade_classifier.fit_transform] group_dims=[21]
[ 2018-07-31 22:12:00,199][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:12:00,200][cascade_classifier.fit_transform] group_ends=[21]
[ 2018-07-31 22:12:00,202][cascade_classifier.fit_transform] X_train.shape=(2410, 21),X_test.shape=(1033, 21)
[ 2018-07-31 22:12:00,203][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(2410, 21), X_cur_test.shape=(1033, 21)
[ 2018-07-31 22:12:01,280][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=97.11%
[ 2018-07-31 22:12:02,746][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=97.10%
[ 2018-07-31 22:12:04,667][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 -

[ 2018-07-31 22:13:00,076][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=98.01%
[ 2018-07-31 22:13:00,077][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=97.87%
[ 2018-07-31 22:13:00,095][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=97.93%
[ 2018-07-31 22:13:00,114][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=97.51%
[ 2018-07-31 22:13:00,138][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=98.34%
[ 2018-07-31 22:13:00,161][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=97.51%
[ 2018-07-31 22:13:00,200][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=97.51%
[ 2018-07-31 22:13:00,215][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=97.93%
[ 

[ 2018-07-31 22:13:49,805][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=97.80%
[ 2018-07-31 22:13:49,807][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=97.87%
[ 2018-07-31 22:13:50,813][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=97.11%
[ 2018-07-31 22:13:52,266][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=98.34%
[ 2018-07-31 22:13:53,735][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=99.17%
[ 2018-07-31 22:13:55,228][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=97.93%
[ 2018-07-31 22:13:56,740][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=96.68%
[ 2018-07-31 22:13:58,809][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=97.93%
[ 

[ 2018-07-31 22:14:50,710][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=97.87%
[ 2018-07-31 22:14:50,711][cascade_classifier.fit_transform] [Result][Optimal Level Detected] opt_layer_num=2, accuracy_train=97.88%, accuracy_test=97.87%


In [9]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

[ 2018-07-31 22:14:50,849][cascade_classifier.transform] X_groups_test.shape=[(1033, 21)]
[ 2018-07-31 22:14:50,857][cascade_classifier.transform] group_dims=[21]
[ 2018-07-31 22:14:50,863][cascade_classifier.transform] X_test.shape=(1033, 21)
[ 2018-07-31 22:14:50,878][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(1033, 21)
[ 2018-07-31 22:14:58,111][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(1033, 27)


Test Accuracy of GCForest = 97.870281 %
(' Time ', '185.08', ' seconds')
[[1003    1]
 [  21    8]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99      1004
        1.0       0.89      0.28      0.42        29

avg / total       0.98      0.98      0.97      1033



# Neural network 

In [10]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
2169/2169 [==============================] - 4s 2ms/step - loss: 0.1692 - acc: 0.9700
Epoch 2/50
2169/2169 [==============================] - 1s 660us/step - loss: 0.1228 - acc: 0.9700
Epoch 3/50
2169/2169 [==============================] - 1s 599us/step - loss: 0.1057 - acc: 0.9700
Epoch 4/50
2169/2169 [==============================] - 1s 658us/step - loss: 0.0998 - acc: 0.9700
Epoch 5/50
2169/2169 [==============================] - 1s 601us/step - loss: 0.0924 - acc: 0.9700
Epoch 6/50
2169/2169 [==============================] - 1s 553us/step - loss: 0.0787 - acc: 0.9719
Epoch 7/50
2169/2169 [==============================] - 1s 546us/step - loss: 0.0756 - acc: 0.9751
Epoch 8/50
2169/2169 [==============================] - 1s 623us/step - loss: 0.0708 - acc: 0.9769
Epoch 9/50
2169/2169 [==============================] - 1s 575us/step - loss: 0.0701 - acc: 0.9779
Epoch 10/50
2169/2169 [==============================] - 1s 586us/step - loss: 0.0617 - acc: 0.9802
Epoch 11/50

2169/2169 [==============================] - 2s 841us/step - loss: 0.0497 - acc: 0.9820
Epoch 33/50
2169/2169 [==============================] - 2s 778us/step - loss: 0.0601 - acc: 0.9825
Epoch 34/50
2169/2169 [==============================] - 2s 866us/step - loss: 0.0528 - acc: 0.9829
Epoch 35/50
2169/2169 [==============================] - 2s 756us/step - loss: 0.0570 - acc: 0.9843
Epoch 36/50
2169/2169 [==============================] - 2s 790us/step - loss: 0.0519 - acc: 0.9848
Epoch 37/50
2169/2169 [==============================] - 2s 827us/step - loss: 0.0528 - acc: 0.9820
Epoch 38/50
2169/2169 [==============================] - 2s 862us/step - loss: 0.0569 - acc: 0.9843
Epoch 39/50
2169/2169 [==============================] - 2s 780us/step - loss: 0.0490 - acc: 0.9852 0s - loss: 0.0451 - acc: 0.9
Epoch 40/50
2169/2169 [==============================] - 1s 615us/step - loss: 0.0485 - acc: 0.9839
Epoch 41/50
2169/2169 [==============================] - 2s 776us/step - loss: 0.05

2169/2169 [==============================] - 1s 618us/step - loss: 0.0681 - acc: 0.9793
Epoch 12/50
2169/2169 [==============================] - 1s 681us/step - loss: 0.0621 - acc: 0.9783
Epoch 13/50
2169/2169 [==============================] - 2s 713us/step - loss: 0.0615 - acc: 0.9820
Epoch 14/50
2169/2169 [==============================] - 2s 708us/step - loss: 0.0610 - acc: 0.9816
Epoch 15/50
2169/2169 [==============================] - 1s 655us/step - loss: 0.0593 - acc: 0.9816
Epoch 16/50
2169/2169 [==============================] - 2s 697us/step - loss: 0.0593 - acc: 0.9820
Epoch 17/50
2169/2169 [==============================] - 1s 542us/step - loss: 0.0546 - acc: 0.9816
Epoch 18/50
2169/2169 [==============================] - 1s 573us/step - loss: 0.0634 - acc: 0.9811
Epoch 19/50
2169/2169 [==============================] - 1s 548us/step - loss: 0.0590 - acc: 0.9793
Epoch 20/50
2169/2169 [==============================] - 1s 510us/step - loss: 0.0570 - acc: 0.9820
Epoch 21/50


Epoch 42/50
2169/2169 [==============================] - 1s 516us/step - loss: 0.0539 - acc: 0.9816
Epoch 43/50
2169/2169 [==============================] - 1s 551us/step - loss: 0.0515 - acc: 0.9852
Epoch 44/50
2169/2169 [==============================] - 1s 528us/step - loss: 0.0489 - acc: 0.9839
Epoch 45/50
2169/2169 [==============================] - 1s 540us/step - loss: 0.0464 - acc: 0.9862
Epoch 46/50
2169/2169 [==============================] - 1s 651us/step - loss: 0.0488 - acc: 0.9852
Epoch 47/50
2169/2169 [==============================] - 1s 661us/step - loss: 0.0513 - acc: 0.9839
Epoch 48/50
2169/2169 [==============================] - 1s 556us/step - loss: 0.0469 - acc: 0.9852
Epoch 49/50
2169/2169 [==============================] - 1s 662us/step - loss: 0.0465 - acc: 0.9866
Epoch 50/50
241/241 [==============================] - 0s 666us/step
Epoch 1/50
2169/2169 [==============================] - 3s 1ms/step - loss: 0.1750 - acc: 0.9714
Epoch 2/50
2169/2169 [============

2169/2169 [==============================] - 1s 565us/step - loss: 0.0545 - acc: 0.9820
Epoch 23/50
2169/2169 [==============================] - 1s 588us/step - loss: 0.0488 - acc: 0.9852
Epoch 24/50
2169/2169 [==============================] - 1s 624us/step - loss: 0.0524 - acc: 0.9829
Epoch 25/50
2169/2169 [==============================] - 1s 574us/step - loss: 0.0539 - acc: 0.9834
Epoch 26/50
2169/2169 [==============================] - 1s 671us/step - loss: 0.0476 - acc: 0.9857
Epoch 27/50
2169/2169 [==============================] - 2s 793us/step - loss: 0.0483 - acc: 0.9839
Epoch 28/50
2169/2169 [==============================] - 1s 624us/step - loss: 0.0509 - acc: 0.9839
Epoch 29/50
2169/2169 [==============================] - 2s 723us/step - loss: 0.0506 - acc: 0.9820
Epoch 30/50
2169/2169 [==============================] - 2s 755us/step - loss: 0.0480 - acc: 0.9811
Epoch 31/50
2169/2169 [==============================] - 1s 687us/step - loss: 0.0492 - acc: 0.9843
Epoch 32/50


2169/2169 [==============================] - 5s 2ms/step - loss: 0.1731 - acc: 0.9539
Epoch 2/50
2169/2169 [==============================] - 2s 741us/step - loss: 0.1208 - acc: 0.9677
Epoch 3/50
2169/2169 [==============================] - 2s 754us/step - loss: 0.1088 - acc: 0.9677
Epoch 4/50
2169/2169 [==============================] - 2s 772us/step - loss: 0.0981 - acc: 0.9677
Epoch 5/50
2169/2169 [==============================] - 2s 766us/step - loss: 0.0851 - acc: 0.9677
Epoch 6/50
2169/2169 [==============================] - 2s 732us/step - loss: 0.0837 - acc: 0.9686
Epoch 7/50
2169/2169 [==============================] - 2s 754us/step - loss: 0.0776 - acc: 0.9733
Epoch 8/50
2169/2169 [==============================] - 2s 694us/step - loss: 0.0701 - acc: 0.9760
Epoch 9/50
2169/2169 [==============================] - 1s 623us/step - loss: 0.0702 - acc: 0.9774
Epoch 10/50
2169/2169 [==============================] - 1s 681us/step - loss: 0.0640 - acc: 0.9765
Epoch 11/50
2169/2169 

2169/2169 [==============================] - 2s 709us/step - loss: 0.0446 - acc: 0.9848
Epoch 33/50
2169/2169 [==============================] - 2s 732us/step - loss: 0.0477 - acc: 0.9848
Epoch 34/50
2169/2169 [==============================] - 1s 682us/step - loss: 0.0455 - acc: 0.9839
Epoch 35/50
2169/2169 [==============================] - 2s 749us/step - loss: 0.0471 - acc: 0.9834
Epoch 36/50
2169/2169 [==============================] - 2s 763us/step - loss: 0.0454 - acc: 0.9843
Epoch 37/50
2169/2169 [==============================] - 2s 741us/step - loss: 0.0489 - acc: 0.9876
Epoch 38/50
2169/2169 [==============================] - 2s 743us/step - loss: 0.0446 - acc: 0.9862
Epoch 39/50
2169/2169 [==============================] - 2s 745us/step - loss: 0.0476 - acc: 0.9839
Epoch 40/50
2169/2169 [==============================] - 2s 754us/step - loss: 0.0440 - acc: 0.9862
Epoch 41/50
2169/2169 [==============================] - 2s 802us/step - loss: 0.0486 - acc: 0.9852
Epoch 42/50


# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 95.740561 %
(' Time ', '0.16', ' seconds')
[[982  22]
 [ 22   7]]


             precision    recall  f1-score   support

        0.0       0.98      0.98      0.98      1004
        1.0       0.24      0.24      0.24        29

avg / total       0.96      0.96      0.96      1033



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 97.386254 %
(' Time ', '3.671', ' seconds')
[[1004    0]
 [  27    2]]


             precision    recall  f1-score   support

        0.0       0.97      1.00      0.99      1004
        1.0       1.00      0.07      0.13        29

avg / total       0.97      0.97      0.96      1033



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 97.289448 %
(' Time ', '2.915', ' seconds')
[[1004    0]
 [  28    1]]


             precision    recall  f1-score   support

        0.0       0.97      1.00      0.99      1004
        1.0       1.00      0.03      0.07        29

avg / total       0.97      0.97      0.96      1033



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 96.708616 %
(' Time ', '3.439', ' seconds')
[[992  12]
 [ 22   7]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.98      1004
        1.0       0.37      0.24      0.29        29

avg / total       0.96      0.97      0.96      1033



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 93.901258 %
(' Time ', '0.018', ' seconds')
[[961  43]
 [ 20   9]]


             precision    recall  f1-score   support

        0.0       0.98      0.96      0.97      1004
        1.0       0.17      0.31      0.22        29

avg / total       0.96      0.94      0.95      1033

